'use client';

/**
 * AiSummaryItem — custom rendering for `activity_type='ai_summary'` rows on
 * the NOC ticket detail timeline (PRD-062 Phase 2).
 *
 * - Cyan-accented card with bot icon + "AI History" header
 * - Disclaimer reminding readers to verify against source facts
 * - Collapsible "View source facts" disclosure showing the raw DrFacts JSON
 * - Manager+ "Regenerate" button calling
 *   POST /api/noc/tickets/{id}/regenerate-ai-summary
 */

import { useState } from 'react';
import { Bot, ChevronRight, RefreshCw, Sparkles } from 'lucide-react';
import { formatDistanceToNow } from 'date-fns';
import { formatDisplayDateTime } from '@/utils/dateFormat';
import { cn } from '@/lib/utils';
import { useAuth } from '@/contexts/AuthContext';
import { UserRole } from '@/types/auth.types';
import type { TicketActivity } from '../../hooks/useTicketActivities';

interface AiSummaryItemProps {
  activity: TicketActivity;
  ticketId: string;
  onRegenerated: () => void;
}

interface AuditPayload {
  facts?: unknown;
  model?: string;
  latency_ms?: number;
}

export function AiSummaryItem({
  activity,
  ticketId,
  onRegenerated,
}: AiSummaryItemProps) {
  // UserRole.PROJECT_MANAGER is the legacy enum value that maps from the
  // 'manager' DB role string in AuthContext.mapRole(). The API gate in
  // /api/noc/tickets/[id]/regenerate-ai-summary checks against the DB
  // string directly, so the two stay aligned via the existing mapper.
  const { hasRole } = useAuth();
  const isManagerPlus =
    hasRole(UserRole.SUPER_ADMIN) ||
    hasRole(UserRole.ADMIN) ||
    hasRole(UserRole.PROJECT_MANAGER);

  const [factsOpen, setFactsOpen] = useState(false);
  const [regenerating, setRegenerating] = useState(false);
  const [regenError, setRegenError] = useState<string | null>(null);

  const audit = !Array.isArray(activity.field_changes)
    ? (activity.field_changes as AuditPayload | null)
    : null;
  const facts = audit?.facts;
  const factsJson = facts ? JSON.stringify(facts, null, 2) : null;

  const handleRegenerate = async () => {
    setRegenerating(true);
    setRegenError(null);
    try {
      const res = await fetch(
        `/api/noc/tickets/${ticketId}/regenerate-ai-summary`,
        { method: 'POST' },
      );
      const body = await res.json().catch(() => null);
      if (!res.ok || !body?.success) {
        throw new Error(body?.error?.message || `HTTP ${res.status}`);
      }
      onRegenerated();
    } catch (err) {
      setRegenError(err instanceof Error ? err.message : 'Regenerate failed');
    } finally {
      setRegenerating(false);
    }
  };

  return (
    <div className="relative pl-8 pb-6">
      <div className="absolute left-[11px] top-8 bottom-0 w-0.5 bg-[var(--ff-border-light)]" />
      <div className="absolute left-0 w-6 h-6 rounded-full flex items-center justify-center border bg-cyan-500/20 text-cyan-400 border-cyan-500/30">
        <Bot className="w-3.5 h-3.5" />
      </div>

      <div className="rounded-lg border border-cyan-500/30 bg-cyan-500/5 p-4 space-y-3">
        <div className="flex items-center justify-between gap-2 flex-wrap">
          <div className="flex items-center gap-2">
            <Sparkles className="w-4 h-4 text-cyan-400" />
            <span className="text-sm font-semibold text-cyan-400">AI History</span>
            <span className="text-xs text-[var(--ff-text-secondary)]">
              {formatDistanceToNow(new Date(activity.created_at), { addSuffix: true })}
            </span>
            {audit?.latency_ms != null && (
              <span className="text-[10px] text-[var(--ff-text-tertiary)]">
                {audit.latency_ms} ms
              </span>
            )}
          </div>
          {isManagerPlus && (
            <button
              type="button"
              onClick={handleRegenerate}
              disabled={regenerating}
              className="text-xs flex items-center gap-1 px-2 py-1 rounded border border-cyan-500/30 text-cyan-400 hover:bg-cyan-500/10 disabled:opacity-50"
              title="Regenerate the AI history summary for this ticket"
            >
              <RefreshCw className={cn('w-3.5 h-3.5', regenerating && 'animate-spin')} />
              Regenerate
            </button>
          )}
        </div>

        <p className="text-xs text-[var(--ff-text-tertiary)] italic">
          Generated by AI from FibreFlow data — verify against source facts before acting.
        </p>

        {activity.description && (
          <div className="text-sm text-[var(--ff-text-primary)] whitespace-pre-wrap leading-relaxed">
            {activity.description}
          </div>
        )}

        {regenError && <p className="text-xs text-red-400">{regenError}</p>}

        {factsJson && (
          <div>
            <button
              type="button"
              onClick={() => setFactsOpen(!factsOpen)}
              className="flex items-center gap-1 text-xs text-[var(--ff-text-secondary)] hover:text-[var(--ff-text-primary)]"
            >
              <ChevronRight
                className={cn('w-3.5 h-3.5 transition-transform', factsOpen && 'rotate-90')}
              />
              View source facts
            </button>
            {factsOpen && (
              <pre className="mt-2 text-[11px] leading-snug overflow-x-auto p-3 rounded bg-[var(--ff-bg-tertiary)] text-[var(--ff-text-secondary)] max-h-96">
                {factsJson}
              </pre>
            )}
          </div>
        )}

        <div className="text-xs text-[var(--ff-text-secondary)]">
          {formatDisplayDateTime(activity.created_at)}
          {audit?.model && (
            <>
              <span className="mx-2 text-[var(--ff-text-tertiary)]">·</span>
              <span className="font-mono text-[10px]">{audit.model}</span>
            </>
          )}
        </div>
      </div>
    </div>
  );
}
