export interface FieldMapping {
  concept: string;
  table: string;
  column: string;
}

export const fieldMappings: FieldMapping[] = [
  // Optical Status / ATP / PON Live
  { concept: "Optical Status / ATP / PON Live", table: "pon_stage_tracking", column: "optical_total" },
  { concept: "Optical Status / ATP / PON Live", table: "pon_stage_tracking", column: "optical_complete" },
  { concept: "Optical Status / ATP / PON Live", table: "pon_stage_tracking", column: "optical_first_date" },
  { concept: "Optical Status / ATP / PON Live", table: "pon_stage_tracking", column: "optical_last_date" },
  { concept: "Optical Status / ATP / PON Live", table: "pon_stage_tracking", column: "atp_total" },
  { concept: "Optical Status / ATP / PON Live", table: "pon_stage_tracking", column: "atp_complete" },
  { concept: "Optical Status / ATP / PON Live", table: "pon_stage_tracking", column: "atp_first_date" },
  { concept: "Optical Status / ATP / PON Live", table: "pon_stage_tracking", column: "atp_last_date" },
  { concept: "Optical Status / ATP / PON Live", table: "sp_pon_tracker", column: "optical_splicing_date" },
  { concept: "Optical Status / ATP / PON Live", table: "sp_pon_tracker", column: "optical_submitted_date" },
  { concept: "Optical Status / ATP / PON Live", table: "sp_pon_tracker", column: "optical_activated_date" },
  { concept: "Optical Status / ATP / PON Live", table: "sp_pon_tracker", column: "atp_qa_approved" },
  { concept: "Optical Status / ATP / PON Live", table: "sp_project_summary", column: "optical_scope" },
  { concept: "Optical Status / ATP / PON Live", table: "sp_project_summary", column: "optical_complete" },
  { concept: "Optical Status / ATP / PON Live", table: "sp_project_summary", column: "pct_optical" },
  { concept: "Optical Status / ATP / PON Live", table: "construction_qa_reviews", column: "optical_step_01_cable_route" },
  { concept: "Optical Status / ATP / PON Live", table: "construction_qa_reviews", column: "optical_step_02_splicing" },
  { concept: "Optical Status / ATP / PON Live", table: "construction_qa_reviews", column: "optical_step_03_testing" },
  { concept: "Optical Status / ATP / PON Live", table: "oes_activations", column: "activation_date" },
  { concept: "Optical Status / ATP / PON Live", table: "oes_activations", column: "oes_status" },
  { concept: "Optical Status / ATP / PON Live", table: "arch_oes_data", column: "activation_date" },
  { concept: "Optical Status / ATP / PON Live", table: "arch_oes_data", column: "oes_activation_id" },
  { concept: "Optical Status / ATP / PON Live", table: "offline_devices", column: "device_not_active_count" },
  { concept: "Optical Status / ATP / PON Live", table: "offline_devices", column: "offline_bucket" },
  // Project Phase / Stage / Status
  { concept: "Project Phase / Stage / Status", table: "projects", column: "status" },
  { concept: "Project Phase / Stage / Status", table: "project_phases", column: "phase_order" },
  { concept: "Project Phase / Stage / Status", table: "project_phases", column: "status" },
  { concept: "Project Phase / Stage / Status", table: "phase_steps", column: "status" },
  { concept: "Project Phase / Stage / Status", table: "phase_steps", column: "step_order" },
  { concept: "Project Phase / Stage / Status", table: "phase_tasks", column: "status" },
  { concept: "Project Phase / Stage / Status", table: "documents", column: "approval_status" },
  { concept: "Project Phase / Stage / Status", table: "boq_approvals", column: "approval_status" },
  { concept: "Project Phase / Stage / Status", table: "contractor_agreements", column: "status" },
  { concept: "Project Phase / Stage / Status", table: "supplier_contracts", column: "status" },
  // CWC (Civil Works) Status
  { concept: "CWC (Civil Works) Status", table: "pon_stage_tracking", column: "cwc_total" },
  { concept: "CWC (Civil Works) Status", table: "pon_stage_tracking", column: "cwc_complete" },
  { concept: "CWC (Civil Works) Status", table: "pon_stage_tracking", column: "cwc_first_date" },
  { concept: "CWC (Civil Works) Status", table: "pon_stage_tracking", column: "cwc_last_date" },
  { concept: "CWC (Civil Works) Status", table: "sp_pon_tracker", column: "cwc_poles_date" },
  { concept: "CWC (Civil Works) Status", table: "sp_pon_tracker", column: "cwc_stringing_date" },
  { concept: "CWC (Civil Works) Status", table: "sp_pon_tracker", column: "cwc_qa_approved" },
  { concept: "CWC (Civil Works) Status", table: "sp_project_summary", column: "cwc_scope" },
  { concept: "CWC (Civil Works) Status", table: "sp_project_summary", column: "cwc_complete" },
  { concept: "CWC (Civil Works) Status", table: "sp_project_summary", column: "pct_cwc" },
  { concept: "CWC (Civil Works) Status", table: "construction_qa_reviews", column: "cwc_step_01_trenching" },
  { concept: "CWC (Civil Works) Status", table: "construction_qa_reviews", column: "cwc_step_02_ducting" },
  { concept: "CWC (Civil Works) Status", table: "construction_qa_reviews", column: "cwc_step_03_reinstatement" },
  // Poles (Planting/Scope/Completion)
  { concept: "Poles (Planting/Scope/Completion)", table: "pon_stage_tracking", column: "poles_total" },
  { concept: "Poles (Planting/Scope/Completion)", table: "pon_stage_tracking", column: "poles_planted" },
  { concept: "Poles (Planting/Scope/Completion)", table: "pon_stage_tracking", column: "poles_first_date" },
  { concept: "Poles (Planting/Scope/Completion)", table: "pon_stage_tracking", column: "poles_last_date" },
  { concept: "Poles (Planting/Scope/Completion)", table: "sp_pon_tracker", column: "scope_poles" },
  { concept: "Poles (Planting/Scope/Completion)", table: "sp_pon_tracker", column: "pole_perm" },
  { concept: "Poles (Planting/Scope/Completion)", table: "sp_pon_tracker", column: "poles_planted" },
  { concept: "Poles (Planting/Scope/Completion)", table: "sp_project_summary", column: "poles_scope" },
  { concept: "Poles (Planting/Scope/Completion)", table: "sp_project_summary", column: "poles_complete" },
  { concept: "Poles (Planting/Scope/Completion)", table: "sp_project_summary", column: "pct_poles" },
  { concept: "Poles (Planting/Scope/Completion)", table: "poles", column: "pole_number" },
  { concept: "Poles (Planting/Scope/Completion)", table: "poles", column: "pole_type" },
  { concept: "Poles (Planting/Scope/Completion)", table: "poles", column: "installation_date" },
  { concept: "Poles (Planting/Scope/Completion)", table: "sow_poles", column: "quantity" },
  { concept: "Poles (Planting/Scope/Completion)", table: "sow_poles", column: "completed_quantity" },
  { concept: "Poles (Planting/Scope/Completion)", table: "onemap_poles", column: "permission_date" },
  { concept: "Poles (Planting/Scope/Completion)", table: "onemap_poles", column: "pole_permission_status" },
  // Sign-ups / Homes / Customers
  { concept: "Sign-ups / Homes / Customers", table: "arch_pon_revenue", column: "homes_count" },
  { concept: "Sign-ups / Homes / Customers", table: "client_purchase_orders", column: "drops_assigned" },
  { concept: "Sign-ups / Homes / Customers", table: "client_purchase_orders", column: "drops_activated" },
  { concept: "Sign-ups / Homes / Customers", table: "onemap_properties", column: "home_signup_date" },
  { concept: "Sign-ups / Homes / Customers", table: "sp_project_summary", column: "signups_scope" },
  { concept: "Sign-ups / Homes / Customers", table: "sp_project_summary", column: "signups_complete" },
  { concept: "Sign-ups / Homes / Customers", table: "sp_project_summary", column: "pct_signups" },
  { concept: "Sign-ups / Homes / Customers", table: "sp_pon_tracker", column: "sign_ups" },
  { concept: "Sign-ups / Homes / Customers", table: "sp_pon_tracker", column: "homes_po" },
  { concept: "Sign-ups / Homes / Customers", table: "sp_pon_tracker", column: "homes_recon" },
  { concept: "Sign-ups / Homes / Customers", table: "drops", column: "drop_number" },
  { concept: "Sign-ups / Homes / Customers", table: "drops", column: "drop_status" },
  // Blockages / Constraints / Permissions
  { concept: "Blockages / Constraints / Permissions", table: "pon_stage_tracking", column: "permissions_total" },
  { concept: "Blockages / Constraints / Permissions", table: "pon_stage_tracking", column: "permissions_approved" },
  { concept: "Blockages / Constraints / Permissions", table: "pon_stage_tracking", column: "permissions_first_date" },
  { concept: "Blockages / Constraints / Permissions", table: "pon_stage_tracking", column: "permissions_last_date" },
  { concept: "Blockages / Constraints / Permissions", table: "sp_pon_tracker", column: "pole_perm" },
  { concept: "Blockages / Constraints / Permissions", table: "sp_pon_tracker", column: "blockage" },
  { concept: "Blockages / Constraints / Permissions", table: "sp_project_summary", column: "permissions_scope" },
  { concept: "Blockages / Constraints / Permissions", table: "sp_project_summary", column: "permissions_complete" },
  { concept: "Blockages / Constraints / Permissions", table: "sp_project_summary", column: "pct_permissions" },
  { concept: "Blockages / Constraints / Permissions", table: "onemap_poles", column: "permission_date" },
  { concept: "Blockages / Constraints / Permissions", table: "onemap_poles", column: "pole_permission_status" },
  { concept: "Blockages / Constraints / Permissions", table: "onemap_poles", column: "pole_permission_agent" },
  // Permissions / Wayleaves / Approvals
  { concept: "Permissions / Wayleaves / Approvals", table: "accounting_adjustments", column: "approved_by" },
  { concept: "Permissions / Wayleaves / Approvals", table: "accounting_adjustments", column: "approved_at" },
  { concept: "Permissions / Wayleaves / Approvals", table: "purchase_orders", column: "approved_by" },
  { concept: "Permissions / Wayleaves / Approvals", table: "purchase_orders", column: "approval_date" },
  { concept: "Permissions / Wayleaves / Approvals", table: "stock_pickings", column: "approved_by" },
  { concept: "Permissions / Wayleaves / Approvals", table: "pon_stage_tracking", column: "permissions_approved" },
];
