/**
 * Markdown Report Generator Service
 * Generates comprehensive, professional markdown reports for DR evaluations
 * Suitable for download, archival, and sharing with clients/contractors
 */

import type { EvaluationResult, StepEvaluationResult } from '../types';

/**
 * Generate comprehensive markdown report for a DR evaluation
 */
export function generateMarkdownReport(evaluation: EvaluationResult): string {
  const {
    dr_number,
    project,
    overall_status,
    average_score,
    total_steps,
    passed_steps,
    step_results,
    evaluation_date,
  } = evaluation;

  const statusEmoji = overall_status === 'PASS' ? '✅' : '❌';
  const passPercentage = Math.round((passed_steps / total_steps) * 100);
  const failedSteps = step_results.filter(s => !s.passed);
  const passedStepsList = step_results.filter(s => s.passed);

  // Generate report
  let report = `# Installation Photo Evaluation Report\n\n`;

  // Header Section
  report += `**DR Number:** ${dr_number}  \n`;
  if (project) {
    report += `**Project:** ${project}  \n`;
  }
  report += `**Evaluation Date:** ${formatDateTime(evaluation_date)}  \n`;
  report += `**Overall Status:** ${statusEmoji} **${overall_status}**  \n\n`;

  // Summary Section
  report += `## 📊 Summary\n\n`;
  report += `| Metric | Value |\n`;
  report += `|--------|-------|\n`;
  report += `| Overall Score | **${average_score.toFixed(1)}/10** |\n`;
  report += `| Steps Passed | **${passed_steps}/${total_steps}** (${passPercentage}%) |\n`;
  report += `| Status | ${statusEmoji} **${overall_status}** |\n\n`;

  // Quick Status Overview
  report += `### Installation Quality Assessment\n\n`;
  if (overall_status === 'PASS') {
    report += `✅ **EXCELLENT WORK!** All required photos meet FibreFlow quality standards.\n\n`;
    report += `The installation demonstrates:\n`;
    report += `- Professional workmanship\n`;
    report += `- Compliance with installation guidelines\n`;
    report += `- Proper documentation of all required steps\n\n`;
  } else {
    report += `❌ **ATTENTION REQUIRED** - Some photos do not meet quality standards.\n\n`;
    report += `**Failed Steps:** ${failedSteps.length}\n`;
    report += `**Action Required:** Review and retake photos for failed steps following installation guidelines.\n\n`;
  }

  // Detailed Step Results
  report += `## 📋 Detailed Step-by-Step Evaluation\n\n`;

  // Group steps by status
  if (passedStepsList.length > 0) {
    report += `### ✅ Passed Steps (${passedStepsList.length}/${total_steps})\n\n`;
    passedStepsList.forEach((step, index) => {
      report += formatStepDetail(step, index + 1);
    });
  }

  if (failedSteps.length > 0) {
    report += `### ❌ Failed Steps (${failedSteps.length}/${total_steps})\n\n`;
    failedSteps.forEach((step, index) => {
      report += formatStepDetail(step, index + 1);
    });
  }

  // Performance Breakdown
  report += `## 📈 Performance Breakdown\n\n`;
  report += formatPerformanceChart(step_results);

  // Recommendations
  report += `## 💡 Recommendations\n\n`;
  if (overall_status === 'PASS') {
    report += `✅ **No action required** - Installation meets all quality standards.\n\n`;
    report += `**Best Practices Observed:**\n`;
    const topSteps = [...step_results].sort((a, b) => b.score - a.score).slice(0, 3);
    topSteps.forEach(step => {
      report += `- ✅ ${step.step_label}: ${step.comment}\n`;
    });
    report += `\n**Keep up the excellent work!**\n\n`;
  } else {
    report += `⚠️ **Action Items:**\n\n`;
    failedSteps.forEach((step, index) => {
      report += `${index + 1}. **${step.step_label}** (Score: ${step.score}/10)\n`;
      report += `   - Issue: ${step.comment}\n`;
      report += `   - Action: Retake photo following installation guidelines\n\n`;
    });
  }

  // Installation Guidelines Reference
  report += `## 📖 Installation Guidelines Reference\n\n`;
  report += `All installation photos must meet the following criteria:\n\n`;
  report += formatInstallationGuidelines();

  // Footer
  report += `---\n\n`;
  report += `**Report Generated:** ${formatDateTime(new Date())}  \n`;
  report += `**Generated By:** FibreFlow AI Photo Evaluation System  \n`;
  report += `**Version:** 2.0 (Smart Batch Evaluation)  \n\n`;
  report += `*This report was automatically generated using AI-powered vision analysis. `;
  report += `For questions or disputes, please contact your project manager.*\n`;

  return report;
}

/**
 * Format a single step detail
 */
function formatStepDetail(step: StepEvaluationResult, displayNumber: number): string {
  const icon = step.passed ? '✅' : '❌';
  const scoreBar = generateScoreBar(step.score);

  let detail = `#### ${displayNumber}. ${icon} ${step.step_label}\n\n`;
  detail += `**Score:** ${step.score}/10 ${scoreBar}  \n`;
  detail += `**Status:** ${step.passed ? 'PASS ✅' : 'FAIL ❌'}  \n`;
  detail += `**Evaluation:** ${step.comment}  \n\n`;

  return detail;
}

/**
 * Generate a visual score bar
 */
function generateScoreBar(score: number): string {
  const filled = Math.round(score);
  const empty = 10 - filled;
  return '`' + '█'.repeat(filled) + '░'.repeat(empty) + '`';
}

/**
 * Format performance chart
 */
function formatPerformanceChart(steps: StepEvaluationResult[]): string {
  let chart = `| Step | Status | Score | Quality |\n`;
  chart += `|------|--------|-------|----------|\n`;

  steps.forEach(step => {
    const icon = step.passed ? '✅' : '❌';
    const scoreBar = generateScoreBar(step.score);
    const quality = getQualityLabel(step.score);
    chart += `| ${step.step_label} | ${icon} | ${step.score}/10 | ${quality} ${scoreBar} |\n`;
  });

  chart += `\n`;
  return chart;
}

/**
 * Get quality label based on score
 */
function getQualityLabel(score: number): string {
  if (score >= 9) return 'Excellent';
  if (score >= 8) return 'Very Good';
  if (score >= 7) return 'Good';
  if (score >= 6) return 'Fair';
  return 'Needs Improvement';
}

/**
 * Format installation guidelines
 */
function formatInstallationGuidelines(): string {
  return `
1. **House Photo**: Clear view of the property showing roof, walls, and surroundings
2. **Cable Span**: Visible cable drop from pole to building entry point
3. **ONT Barcode**: Clear, readable barcode label on ONT device
4. **ONT Installation**: Properly mounted ONT with visible connections
5. **Power Supply**: Power adapter connected and cable management visible
6. **Cable Management**: Clean cable routing with proper fastening
7. **Drop Cable**: Exterior cable installation from entry to ONT location
8. **Splice Closure**: If applicable, splice point properly sealed
9. **Inside Wiring**: Interior cable routing from entry point to ONT
10. **Speed Test**: Speed test results or ONT status lights (all green)
11. **Customer Equipment**: Router/ONT device installed and operational
12. **Customer Signature**: Signed installation completion form (if required)

**Photo Quality Standards:**
- Clear focus (not blurry)
- Good lighting (avoid dark/overexposed photos)
- Complete view (all relevant elements visible)
- Proper framing (subject centered and clear)
- Readable text/labels (barcodes, labels, DR numbers)

`;
}

/**
 * Format date and time
 */
function formatDateTime(date: Date): string {
  return new Intl.DateTimeFormat('en-ZA', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
    timeZoneName: 'short',
  }).format(new Date(date));
}

/**
 * Generate filename for markdown report
 */
export function generateReportFilename(dr_number: string, evaluation_date: Date): string {
  const dateStr = new Date(evaluation_date).toISOString().split('T')[0]; // YYYY-MM-DD
  return `FibreFlow_Evaluation_${dr_number}_${dateStr}.md`;
}
