export {
  // Core
  VLM_API_URL,
  VLM_CHAT_ENDPOINT,
  VLM_MODELS_ENDPOINT,
  VLM_MODEL,

  // Per-task model overrides
  VLM_CATEGORIZATION_MODEL,
  VLM_QA_MODEL,
  VLM_EXTRACTION_MODEL,
  VLM_FLEET_MODEL,

  // Image processing
  VLM_MAX_IMAGE_WIDTH,
  VLM_MAX_IMAGE_HEIGHT,
  VLM_JPEG_QUALITY,

  // Timeouts
  VLM_TIMEOUT_DEFAULT,
  VLM_TIMEOUT_REALTIME,
  VLM_TIMEOUT_BATCH,
  VLM_TIMEOUT_QA,
  VLM_TIMEOUT_DOCUMENT,

  // Token limits
  VLM_MAX_TOKENS_DEFAULT,
  VLM_MAX_TOKENS_CATEGORIZATION,
  VLM_MAX_TOKENS_QA,
  VLM_MAX_TOKENS_DOCUMENT,
  VLM_MAX_TOKENS_QUICK,
  VLM_MAX_TOKENS_OCR,
  VLM_MAX_TOKENS_ANALYSIS,

  // Batch/temperature
  VLM_BATCH_SIZE,
  VLM_TEMPERATURE,

  // Health
  VLM_HEALTH_TIMEOUT,
  checkVlmHealth,

  // Utilities
  stripThinkTags,
} from './config';
