"""Endpoint discovery: the two tools that read apps/ff_mcp/endpoints.json.

Split from tools.py to stay inside the project's 300-line file limit. The catalogue is
generated by `npm run mcp:catalogue`; it is data, not a security control.
"""

from __future__ import annotations

import json
from pathlib import Path

from .server import mcp

CATALOGUE_PATH = Path(__file__).with_name("endpoints.json")

MAX_ROWS = 200


def _load_routes() -> list[dict]:
    data = json.loads(CATALOGUE_PATH.read_text())
    return data.get("routes", [])


@mcp.tool()
def list_endpoints(filter: str = "", group: str = "") -> str:
    """Discover FibreFlow API endpoints. Call this FIRST, before fibreflow_get, whenever
    you are not certain a path exists.

    FibreFlow has hundreds of read endpoints; guessing a path wastes a call and can make
    you conclude data is missing when it is not. Filter by keyword (matches the path and
    description) or by group (the first path segment, e.g. "projects", "noc", "fleet").
    Results are capped, and the reply states how many matched in total — if the total
    exceeds what is shown, narrow the filter rather than assuming you have seen
    everything.
    """
    routes = _load_routes()
    needle = filter.strip().lower()
    wanted_group = group.strip().lower()

    matched = [
        r
        for r in routes
        if (not wanted_group or r.get("group", "").lower() == wanted_group)
        and (
            not needle
            or needle in r.get("path", "").lower()
            or needle in (r.get("description") or "").lower()
        )
    ]

    shown = matched[:MAX_ROWS]
    payload = {
        "matched": len(matched),
        "shown": len(shown),
        "truncated": len(matched) > len(shown),
        "routes": shown,
    }
    if payload["truncated"]:
        payload["note"] = (
            f"{len(matched)} endpoints matched; showing the first {len(shown)}. "
            "Narrow with a more specific filter or a group to see the rest."
        )
    if not matched:
        payload["note"] = (
            "Nothing matched. Try a broader keyword, or call list_endpoints with no "
            "arguments to see the available groups."
        )
    return json.dumps(payload, indent=2)


@mcp.tool()
def describe_endpoint(path: str) -> str:
    """Show what a specific FibreFlow endpoint accepts before you call it.

    Use this when list_endpoints has given you a path containing :params (e.g.
    /api/projects/:projectId) so you know which values you must supply. Returns the
    methods, the description, and the required path parameters.
    """
    wanted = path.strip()
    for route in _load_routes():
        if route.get("path") == wanted:
            params = [
                seg[1:] for seg in route["path"].split("/") if seg.startswith(":")
            ]
            return json.dumps(
                {
                    "path": route["path"],
                    "methods": route.get("methods", []),
                    "group": route.get("group"),
                    "description": route.get("description"),
                    "pathParams": params,
                    "note": (
                        "Substitute a real value for each pathParam before calling "
                        "fibreflow_get."
                        if params
                        else None
                    ),
                },
                indent=2,
            )
    return json.dumps(
        {
            "error": f"No catalogued endpoint matches {wanted!r}.",
            "hint": "Call list_endpoints with a keyword to find the correct path.",
        },
        indent=2,
    )
