/**
 * Staff Document Verification API
 * POST /api/staff-documents/[documentId]/verify
 * Verify or reject a staff document
 */

import type { NextApiRequest, NextApiResponse } from 'next';
import { neon } from '@neondatabase/serverless';
import { withAuth, type AuthenticatedNextApiRequest } from '@/lib/auth';
import { withArcjetProtection, aj } from '@/lib/arcjet';
import { createLogger } from '@/lib/logger';
import { recordOcrCorrections } from '@/modules/qa-learning';
import { logDocumentVerified, logDocumentRejected } from '@/services/staff/staffAuditService';
import { log } from '@/lib/logger';
import { apiResponse } from '@/lib/apiResponse';

const sql = neon(process.env.DATABASE_URL || '');
const logger = createLogger('StaffDocumentVerifyAPI');

// Helper to get verifier name
async function getVerifierName(verifierId: string): Promise<string> {
  try {
    const [verifier] = await sql`SELECT name FROM staff WHERE id = ${verifierId}`;
    return (verifier?.name as string) || 'Unknown';
  } catch {
    log.error('VerifyApi', 'Operation failed', { error });
    return 'Unknown';
  }
}

async function handler(req: NextApiRequest, res: NextApiResponse) {
  if (req.method !== 'POST') {
    return apiResponse.methodNotAllowed(res, req.method!, ['POST']);
  }

  const { documentId } = req.query;

  if (!documentId || typeof documentId !== 'string') {
    return apiResponse.badRequest(res, 'Document ID is required');
  }

  try {
    const { status, notes, ocrMetadata: editedOcrMetadata } = req.body;

    // Validate status
    if (!status || !['verified', 'rejected'].includes(status)) {
      return res.status(400).json({
        error: 'Invalid status. Must be "verified" or "rejected"',
      });
    }

    // Get original document to compare OCR values for HITL learning
    const [originalDoc] = await sql`
      SELECT document_type, ocr_metadata, staff_id FROM staff_documents WHERE id = ${documentId}
    `;

    if (!originalDoc) {
      return apiResponse.notFound(res, 'Document not found');
    }

    const documentType = originalDoc.document_type as string;
    const originalOcrMetadata = (originalDoc.ocr_metadata || {}) as Record<string, string>;

    // Get the current user for verifier ID from Clerk (needed for HITL recording)
    const userId = (req as AuthenticatedNextApiRequest).user.id;
    // If edited OCR metadata provided, update the document first
    if (editedOcrMetadata && Object.keys(editedOcrMetadata).length > 0) {
      await sql`
        UPDATE staff_documents
        SET ocr_metadata = ${JSON.stringify(editedOcrMetadata)}::jsonb,
            updated_at = NOW()
        WHERE id = ${documentId}
      `;
      logger.info('Updated OCR metadata before verification', { documentId, fields: Object.keys(editedOcrMetadata) });

      // Record HITL corrections for any fields that were changed
      // This helps improve future VLM OCR extractions
      if (status === 'verified') {
        await recordOcrCorrectionsFromVerification(
          documentType,
          originalOcrMetadata,
          editedOcrMetadata,
          documentId,
          userId || 'unknown'
        );
      }
    }

    // Find staff member by user_id if available
    // Note: userId might be a demo/mock value, so we handle gracefully
    let verifierId: string | null = null;
    if (userId) {
      try {
        const [staffMember] = await sql`
          SELECT id FROM staff WHERE user_id = ${userId}
        `;
        if (staffMember) {
          verifierId = staffMember.id as string;
        }
      } catch {
        // User ID not found or invalid format - continue without verifier
        logger.warn('Could not find staff member for user', { userId });
      }
    }

    // Update document verification status
    const [updated] = await sql`
      UPDATE staff_documents
      SET
        verification_status = ${status},
        verified_by = ${verifierId},
        verified_at = NOW(),
        verification_notes = ${notes || null},
        updated_at = NOW()
      WHERE id = ${documentId}
      RETURNING *
    `;

    if (!updated) {
      return apiResponse.notFound(res, 'Document not found');
    }

    logger.info('Document verification updated', { documentId, status, verifierId });

    // If document is verified, sync OCR metadata to staff table and generate auto-notes
    let autoGeneratedNotes = '';
    if (status === 'verified') {
      const syncedFields = await syncOcrMetadataToStaff(updated as Record<string, unknown>);

      // Auto-generate verification notes if fields were synced
      if (syncedFields.length > 0) {
        const timestamp = new Date().toISOString().split('T')[0];
        autoGeneratedNotes = `[${timestamp}] ✅ Verified and synced to staff record:\n• ${syncedFields.join('\n• ')}`;

        // Append auto-generated notes to user notes
        const finalNotes = notes?.trim()
          ? `${notes.trim()}\n\n${autoGeneratedNotes}`
          : autoGeneratedNotes;

        // Update the verification notes with auto-generated content
        await sql`
          UPDATE staff_documents
          SET verification_notes = ${finalNotes}
          WHERE id = ${documentId}
        `;

        logger.info('Auto-generated verification notes', {
          documentId,
          syncedFieldCount: syncedFields.length,
        });
      }

      // Log to audit trail
      const staffId = (updated as Record<string, unknown>).staff_id as string;
      const verifierName = verifierId ? await getVerifierName(verifierId) : 'System';
      await logDocumentVerified(
        staffId,
        documentType,
        syncedFields,
        verifierName,
        req.headers['x-forwarded-for'] as string || req.socket?.remoteAddress
      );
    } else if (status === 'rejected') {
      // Log rejection to audit trail
      const staffId = (updated as Record<string, unknown>).staff_id as string;
      const verifierName = verifierId ? await getVerifierName(verifierId) : 'System';
      await logDocumentRejected(
        staffId,
        documentType,
        notes || 'No reason provided',
        verifierName,
        req.headers['x-forwarded-for'] as string || req.socket?.remoteAddress
      );
    }

    // Get full document with joins
    const [document] = await sql`
      SELECT
        sd.*,
        CONCAT(s.first_name, ' ', s.last_name) as staff_name,
        CONCAT(v.first_name, ' ', v.last_name) as verifier_name
      FROM staff_documents sd
      LEFT JOIN staff s ON s.id = sd.staff_id
      LEFT JOIN staff v ON v.id = sd.verified_by
      WHERE sd.id = ${documentId}
    `;

    if (!document) {
      return apiResponse.notFound(res, 'Document not found after verification');
    }

    return res.status(200).json({
      success: true,
      document: mapDbToDocument(document as Record<string, unknown>),
    });
  } catch (error: unknown) {
    const errorMessage = error instanceof Error ? error.message : 'Unknown error';
    logger.error('Failed to verify document', { documentId, error: errorMessage });
    return res.status(500).json({ error: 'Failed to verify document', message: errorMessage });
  }
}

export default withAuth(withArcjetProtection(handler, aj));

// Map database row to StaffDocument interface
function mapDbToDocument(row: Record<string, unknown>) {
  return {
    id: row.id,
    staffId: row.staff_id,
    documentType: row.document_type,
    documentName: row.document_name,
    fileUrl: row.file_url,
    fileSize: row.file_size,
    mimeType: row.mime_type,
    expiryDate: row.expiry_date ? new Date(row.expiry_date as string).toISOString() : undefined,
    issuedDate: row.issued_date ? new Date(row.issued_date as string).toISOString() : undefined,
    issuingAuthority: row.issuing_authority,
    documentNumber: row.document_number,
    verificationStatus: row.verification_status,
    verifiedBy: row.verified_by,
    verifiedAt: row.verified_at ? new Date(row.verified_at as string).toISOString() : undefined,
    verificationNotes: row.verification_notes,
    ocrMetadata: row.ocr_metadata || undefined,
    createdAt: new Date(row.created_at as string).toISOString(),
    updatedAt: new Date(row.updated_at as string).toISOString(),
    staff: row.staff_name ? { id: row.staff_id, name: row.staff_name } : undefined,
    verifier: row.verifier_name ? { id: row.verified_by, name: row.verifier_name } : undefined,
  };
}

/**
 * Sync OCR metadata to staff table when document is verified
 * This is called after successful verification to populate staff fields
 * Compulsory docs: SA ID, Passport, Driver's License, Bank Details
 * Returns list of fields that were synced (for auto-generated notes)
 */
async function syncOcrMetadataToStaff(document: Record<string, unknown>): Promise<string[]> {
  const staffId = document.staff_id as string;
  const documentType = document.document_type as string;
  const ocrMetadata = document.ocr_metadata as Record<string, string> | null;

  if (!staffId || !ocrMetadata || Object.keys(ocrMetadata).length === 0) {
    return [];
  }

  try {
    // Build auto-generated verification notes
    const syncedFields: string[] = [];

    switch (documentType) {
      case 'sa_id':
        // Sync SA ID and all related fields to staff table
        const saIdNumber = ocrMetadata.saIdNumber || ocrMetadata.documentNumber || ocrMetadata.idNumber;
        const saIdDob = ocrMetadata.dateOfBirth;
        const saIdGender = ocrMetadata.gender;
        const saIdNationality = ocrMetadata.citizenship || ocrMetadata.nationality;
        const saIdCountryOfBirth = ocrMetadata.countryOfBirth;
        const saIdFullName = ocrMetadata.fullName || `${ocrMetadata.firstName || ''} ${ocrMetadata.surname || ''}`.trim();

        if (saIdNumber || saIdDob || saIdGender || saIdNationality || saIdCountryOfBirth) {
          await sql`
            UPDATE staff
            SET
              sa_id_number = COALESCE(${saIdNumber || null}, sa_id_number),
              date_of_birth = COALESCE(${saIdDob ? new Date(saIdDob) : null}, date_of_birth),
              gender = COALESCE(${saIdGender || null}, gender),
              nationality = COALESCE(${saIdNationality || null}, nationality),
              country_of_birth = COALESCE(${saIdCountryOfBirth || null}, country_of_birth),
              updated_at = NOW()
            WHERE id = ${staffId}
          `;

          if (saIdNumber) syncedFields.push(`SA ID: ${saIdNumber}`);
          if (saIdDob) syncedFields.push(`DOB: ${saIdDob}`);
          if (saIdGender) syncedFields.push(`Gender: ${saIdGender}`);
          if (saIdNationality) syncedFields.push(`Nationality: ${saIdNationality}`);
          if (saIdCountryOfBirth) syncedFields.push(`Country of Birth: ${saIdCountryOfBirth}`);

          logger.info('Synced SA ID data from verified document', {
            staffId,
            saIdNumber,
            dateOfBirth: saIdDob,
            gender: saIdGender,
            fieldsUpdated: syncedFields.length,
          });
        }
        break;

      case 'passport':
        // Sync passport details to staff table
        // Check both original VLM field names AND mapped field names
        const passportNumber = ocrMetadata.passportNumber || ocrMetadata.documentNumber;
        const passportExpiry = ocrMetadata.passportExpiry || ocrMetadata.dateOfExpiry || ocrMetadata.expiryDate;
        const passportCountry = ocrMetadata.passportCountry || ocrMetadata.issuingAuthority;
        const passportDob = ocrMetadata.dateOfBirth;
        const passportGender = ocrMetadata.gender;
        const passportNationality = ocrMetadata.nationality;
        const passportPlaceOfBirth = ocrMetadata.placeOfBirth;
        const passportIssueDate = ocrMetadata.dateOfIssue || ocrMetadata.issuedDate;

        if (passportNumber || passportExpiry || passportCountry || passportDob || passportNationality) {
          await sql`
            UPDATE staff
            SET
              passport_number = COALESCE(${passportNumber || null}, passport_number),
              passport_expiry = COALESCE(${passportExpiry ? new Date(passportExpiry) : null}, passport_expiry),
              passport_country = COALESCE(${passportCountry || null}, passport_country),
              date_of_birth = COALESCE(${passportDob ? new Date(passportDob) : null}, date_of_birth),
              gender = COALESCE(${passportGender || null}, gender),
              nationality = COALESCE(${passportNationality || null}, nationality),
              country_of_birth = COALESCE(${passportPlaceOfBirth || null}, country_of_birth),
              updated_at = NOW()
            WHERE id = ${staffId}
          `;

          if (passportNumber) syncedFields.push(`Passport: ${passportNumber}`);
          if (passportExpiry) syncedFields.push(`Passport Expiry: ${passportExpiry}`);
          if (passportIssueDate) syncedFields.push(`Issue Date: ${passportIssueDate}`);
          if (passportCountry) syncedFields.push(`Issuing Country: ${passportCountry}`);
          if (passportDob) syncedFields.push(`DOB: ${passportDob}`);
          if (passportGender) syncedFields.push(`Gender: ${passportGender}`);
          if (passportNationality) syncedFields.push(`Nationality: ${passportNationality}`);
          if (passportPlaceOfBirth) syncedFields.push(`Place of Birth: ${passportPlaceOfBirth}`);

          logger.info('Synced passport from verified document', {
            staffId,
            passportNumber,
            passportExpiry,
            fieldsUpdated: syncedFields.length,
          });
        }
        break;

      case 'drivers_license':
        // Sync driver's license details to staff table
        // Check both original VLM field names AND mapped field names
        const dlNumber = ocrMetadata.driversLicenseNumber || ocrMetadata.licenseNumber;
        const dlIdNumber = ocrMetadata.idNumber || ocrMetadata.documentNumber;
        const dlExpiry = ocrMetadata.driversLicenseExpiry || ocrMetadata.validTo || ocrMetadata.expiryDate;
        const dlValidFrom = ocrMetadata.validFrom;
        const dlCodes = ocrMetadata.driversLicenseCodes || ocrMetadata.licenseCodes;
        const dlDob = ocrMetadata.dateOfBirth;
        const dlFullName = ocrMetadata.fullName;
        const dlRestrictions = ocrMetadata.restrictions;

        if (dlNumber || dlExpiry || dlCodes || dlDob || dlIdNumber) {
          await sql`
            UPDATE staff
            SET
              drivers_license_number = COALESCE(${dlNumber || null}, drivers_license_number),
              drivers_license_expiry = COALESCE(${dlExpiry ? new Date(dlExpiry) : null}, drivers_license_expiry),
              sa_id_number = COALESCE(${dlIdNumber || null}, sa_id_number),
              date_of_birth = COALESCE(${dlDob ? new Date(dlDob) : null}, date_of_birth),
              updated_at = NOW()
            WHERE id = ${staffId}
          `;

          if (dlNumber) syncedFields.push(`License: ${dlNumber}`);
          if (dlIdNumber) syncedFields.push(`SA ID (from DL): ${dlIdNumber}`);
          if (dlExpiry) syncedFields.push(`License Expiry: ${dlExpiry}`);
          if (dlValidFrom) syncedFields.push(`Valid From: ${dlValidFrom}`);
          if (dlCodes) syncedFields.push(`License Codes: ${dlCodes}`);
          if (dlDob) syncedFields.push(`DOB: ${dlDob}`);
          if (dlRestrictions) syncedFields.push(`Restrictions: ${dlRestrictions}`);

          logger.info('Synced drivers license from verified document', {
            staffId,
            licenseNumber: dlNumber,
            licenseCodes: dlCodes,
            expiry: dlExpiry,
            fieldsUpdated: syncedFields.length,
          });
        }
        break;

      case 'bank_details':
      case 'bank_statement':
        // Sync bank details to staff table
        const bankName = ocrMetadata.bankName;
        const bankAccountNumber = ocrMetadata.bankAccountNumber || ocrMetadata.accountNumber;
        const bankBranchCode = ocrMetadata.bankBranchCode || ocrMetadata.branchCode;
        const bankAccountType = ocrMetadata.bankAccountType || ocrMetadata.accountType;
        const bankAccountHolder = ocrMetadata.bankAccountHolder || ocrMetadata.accountHolder;

        if (bankName || bankAccountNumber || bankBranchCode || bankAccountType || bankAccountHolder) {
          await sql`
            UPDATE staff
            SET
              bank_name = COALESCE(${bankName || null}, bank_name),
              bank_account_number = COALESCE(${bankAccountNumber || null}, bank_account_number),
              bank_branch_code = COALESCE(${bankBranchCode || null}, bank_branch_code),
              bank_account_type = COALESCE(${bankAccountType?.toLowerCase() || null}, bank_account_type),
              bank_account_holder = COALESCE(${bankAccountHolder || null}, bank_account_holder),
              bank_details_verified_at = NOW(),
              updated_at = NOW()
            WHERE id = ${staffId}
          `;

          if (bankName) syncedFields.push(`Bank: ${bankName}`);
          if (bankAccountNumber) syncedFields.push(`Account: ****${bankAccountNumber.slice(-4)}`);
          if (bankBranchCode) syncedFields.push(`Branch: ${bankBranchCode}`);
          if (bankAccountType) syncedFields.push(`Type: ${bankAccountType}`);

          logger.info('Synced bank details from verified document', {
            staffId,
            documentType,
            bankName,
            accountNumber: bankAccountNumber ? `****${bankAccountNumber.slice(-4)}` : null,
          });
        }
        break;

      case 'employment_contract':
        // Sync employment contract details
        const contractSalary = ocrMetadata.salary;
        const contractStartDate = ocrMetadata.startDate;
        const contractJobTitle = ocrMetadata.jobTitle || ocrMetadata.position;
        const contractEmploymentType = ocrMetadata.employmentType;
        const employeeSigned = ocrMetadata.employeeSigned;
        const employerSigned = ocrMetadata.employerSigned;

        if (contractSalary || contractStartDate || contractJobTitle || contractEmploymentType) {
          // Parse salary if it's a string with currency
          let salaryValue = null;
          if (contractSalary) {
            const salaryMatch = String(contractSalary).replace(/[R\s,]/g, '').match(/[\d.]+/);
            if (salaryMatch) {
              salaryValue = parseFloat(salaryMatch[0]);
            }
          }

          await sql`
            UPDATE staff
            SET
              salary = COALESCE(${salaryValue}, salary),
              join_date = COALESCE(${contractStartDate ? new Date(contractStartDate) : null}, join_date),
              position = COALESCE(${contractJobTitle || null}, position),
              contract_type = COALESCE(${contractEmploymentType || null}, contract_type),
              updated_at = NOW()
            WHERE id = ${staffId}
          `;

          if (contractSalary) syncedFields.push(`Salary: ${contractSalary}`);
          if (contractStartDate) syncedFields.push(`Start Date: ${contractStartDate}`);
          if (contractJobTitle) syncedFields.push(`Position: ${contractJobTitle}`);
          if (contractEmploymentType) syncedFields.push(`Contract Type: ${contractEmploymentType}`);
          if (employeeSigned) syncedFields.push(`Employee Signed: ${employeeSigned}`);
          if (employerSigned) syncedFields.push(`Employer Signed: ${employerSigned}`);

          logger.info('Synced employment contract from verified document', {
            staffId,
            salary: salaryValue,
            startDate: contractStartDate,
            jobTitle: contractJobTitle,
          });
        }
        break;

      default:
        break;
    }

    // If any fields were synced, also append to staff's notes field for audit trail
    if (syncedFields.length > 0) {
      await appendToStaffNotes(staffId, documentType, syncedFields);
    }

    // Return synced fields for auto-generated notes
    return syncedFields;
  } catch (error) {
    // Log but don't fail verification if sync fails
    logger.warn('Failed to sync OCR metadata to staff table', {
      staffId,
      documentType,
      error: error instanceof Error ? error.message : 'Unknown error',
    });
    return [];
  }
}

/**
 * Create document verification note in staff_notes table
 * Creates an audit trail of verified documents that shows in the Notes tab
 */
async function appendToStaffNotes(
  staffId: string,
  documentType: string,
  syncedFields: string[],
  verifierName?: string
): Promise<void> {
  try {
    const docTypeLabel = formatDocumentType(documentType);
    const noteTitle = `${docTypeLabel} Verified`;

    // Prevent duplicates - check if same note was created in last 30 seconds
    const [existing] = await sql`
      SELECT id FROM staff_notes
      WHERE staff_id = ${staffId}::uuid
        AND title = ${noteTitle}
        AND created_at > NOW() - INTERVAL '30 seconds'
      LIMIT 1
    `;

    if (existing) {
      logger.info('Skipping duplicate note creation', { staffId, documentType });
      return;
    }

    // Build the note content with summary and details
    const noteContent = JSON.stringify({
      summary: `${docTypeLabel} verified and ${syncedFields.length} fields synced`,
      verifiedBy: verifierName || 'System',
      fields: syncedFields,
    });

    // Insert into staff_notes table (matches NotesTab component)
    await sql`
      INSERT INTO staff_notes (id, staff_id, note_type, title, content, created_by_name, metadata, created_at, updated_at)
      VALUES (
        gen_random_uuid(),
        ${staffId}::uuid,
        'document_note',
        ${noteTitle},
        ${noteContent},
        ${verifierName || 'System (OCR)'},
        ${JSON.stringify({ documentType, fieldCount: syncedFields.length })}::jsonb,
        NOW(),
        NOW()
      )
    `;

    logger.info('Created OCR verification note', {
      staffId,
      documentType,
      fieldsCount: syncedFields.length,
    });
  } catch (error) {
    // Don't fail verification if notes creation fails
    logger.warn('Failed to create staff note', {
      staffId,
      documentType,
      error: error instanceof Error ? error.message : 'Unknown error',
    });
  }
}

/**
 * Format document type for display in notes
 */
function formatDocumentType(documentType: string): string {
  const labels: Record<string, string> = {
    sa_id: 'SA ID Document',
    passport: 'Passport',
    drivers_license: "Driver's License",
    bank_details: 'Bank Details',
    bank_statement: 'Bank Statement',
    employment_contract: 'Employment Contract',
    medical_certificate: 'Medical Certificate',
    police_clearance: 'Police Clearance',
  };
  return labels[documentType] || documentType.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase());
}

/**
 * Record HITL corrections when a human edits OCR-extracted values during verification
 * These corrections are used as few-shot examples to improve future VLM extractions
 */
async function recordOcrCorrectionsFromVerification(
  documentType: string,
  originalOcr: Record<string, string>,
  editedOcr: Record<string, string>,
  documentId: string,
  correctedBy: string
): Promise<void> {
  try {
    const corrections = [];

    // Compare all fields and record any that were changed
    for (const [fieldName, correctedValue] of Object.entries(editedOcr)) {
      const originalValue = originalOcr[fieldName];

      // Skip if values are the same (no correction made)
      if (originalValue === correctedValue) continue;

      // Skip empty corrections
      if (!correctedValue || correctedValue.trim() === '') continue;

      corrections.push({
        moduleName: 'staff_documents',
        documentType,
        fieldName,
        vlmExtractedValue: originalValue || null,
        correctedValue: correctedValue.trim(),
        correctedBy,
        sourceRecordId: documentId,
        sourceTable: 'staff_documents',
        correctionReason: originalValue
          ? `Human corrected "${originalValue}" to "${correctedValue}" during document verification`
          : `Human added value "${correctedValue}" that was not detected by OCR`,
      });
    }

    if (corrections.length > 0) {
      await recordOcrCorrections(corrections);
      logger.info('Recorded HITL OCR corrections', {
        documentType,
        correctionCount: corrections.length,
        fields: corrections.map(c => c.fieldName),
      });
    }
  } catch (error) {
    // Don't fail verification if HITL recording fails
    logger.warn('Failed to record HITL OCR corrections', {
      documentType,
      documentId,
      error: error instanceof Error ? error.message : 'Unknown error',
    });
  }
}
