/**
 * FibreFlow User Manual Content
 * 
 * Auto-generated from docs/user-manuals/source/fibreflow-complete.md
 * Last updated: 2026-02-11T02:11:11.002Z
 * 
 * DO NOT EDIT THIS FILE MANUALLY - run `npm run embed-manual` to regenerate
 */

const MANUAL_CONTENT = `---
pdf_options:
  format: A4
  margin:
    top: 25mm
    bottom: 25mm
    left: 20mm
    right: 20mm
  displayHeaderFooter: true
  headerTemplate: |-
    <style>
      section { width: 100%; font-family: 'IBM Plex Sans', Helvetica, Arial, sans-serif; font-size: 8px; color: #666; padding: 0 20mm; }
      .header-line { border-bottom: 2px solid #219ebc; padding-bottom: 4px; display: flex; justify-content: space-between; }
    </style>
    <section>
      <div class="header-line">
        <span style="color: #023047; font-weight: 600;">VELOCITY FIBRE</span>
        <span>FibreFlow — Complete User Manual v1.3</span>
      </div>
    </section>
  footerTemplate: |-
    <style>
      section { width: 100%; font-family: 'IBM Plex Sans', Helvetica, Arial, sans-serif; font-size: 8px; color: #666; padding: 0 20mm; }
      .footer-line { border-top: 1px solid #219ebc; padding-top: 4px; display: flex; justify-content: space-between; }
    </style>
    <section>
      <div class="footer-line">
        <span>Confidential — Velocity Fibre (Pty) Ltd</span>
        <span>Page <span class="pageNumber"></span> of <span class="totalPages"></span></span>
      </div>
    </section>
body_class: velocity-manual
css: |-
  :root {
    --vf-navy: #023047;
    --vf-blue: #1e73be;
    --vf-teal: #219ebc;
    --vf-sky: #2ea3f2;
    --vf-dark: #0e0c19;
    --vf-body: #3c3a47;
    --vf-gray-bg: #f9f9f9;
    --vf-light-border: #e0e0e0;
    --vf-red-accent: #8b2346;
  }
  @import url('https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@400;500;600;700&family=IBM+Plex+Sans+Condensed:wght@400;500;600&display=swap');
  body {
    font-family: 'IBM Plex Sans', Helvetica, Arial, sans-serif;
    color: var(--vf-body);
    line-height: 1.6;
    font-size: 11pt;
  }
  .cover-page {
    page-break-after: always;
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    min-height: 85vh;
    text-align: center;
    padding: 40px;
  }
  .cover-page img { width: 220px; margin-bottom: 40px; }
  .cover-title {
    font-family: 'IBM Plex Sans Condensed', Helvetica, Arial, sans-serif;
    font-size: 36pt; font-weight: 500; color: var(--vf-navy);
    margin: 0 0 8px 0; line-height: 1.2;
  }
  .cover-subtitle {
    font-size: 16pt; color: var(--vf-teal); font-weight: 500;
    margin: 0 0 40px 0; letter-spacing: 1px;
  }
  .cover-divider {
    width: 80px; height: 3px;
    background: linear-gradient(90deg, var(--vf-navy), var(--vf-teal));
    margin: 0 auto 40px; border: none;
  }
  .cover-meta { font-size: 10pt; color: #666; line-height: 2; }
  .cover-meta strong { color: var(--vf-navy); }
  .cover-footer {
    margin-top: 60px; padding-top: 20px;
    border-top: 2px solid var(--vf-teal);
    font-size: 9pt; color: #999;
  }
  h1 {
    font-family: 'IBM Plex Sans Condensed', Helvetica, Arial, sans-serif;
    font-size: 26pt; font-weight: 500; color: var(--vf-navy);
    border-bottom: 3px solid var(--vf-teal); padding-bottom: 8px; margin-top: 40px;
  }
  h2 {
    font-family: 'IBM Plex Sans Condensed', Helvetica, Arial, sans-serif;
    font-size: 18pt; font-weight: 500; color: var(--vf-navy);
    border-bottom: 2px solid var(--vf-teal); padding-bottom: 6px;
    margin-top: 30px; page-break-after: avoid;
  }
  h3 {
    font-family: 'IBM Plex Sans', Helvetica, Arial, sans-serif;
    font-size: 13pt; font-weight: 600; color: var(--vf-navy);
    margin-top: 20px; page-break-after: avoid;
  }
  h4 {
    font-family: 'IBM Plex Sans', Helvetica, Arial, sans-serif;
    font-size: 11pt; font-weight: 600; color: var(--vf-teal);
    text-transform: uppercase; letter-spacing: 0.5px;
  }
  table {
    width: 100%; border-collapse: collapse; margin: 16px 0;
    font-size: 10pt; page-break-inside: avoid;
  }
  thead th {
    background-color: var(--vf-navy); color: white; font-weight: 600;
    padding: 10px 12px; text-align: left; font-size: 9.5pt;
  }
  tbody td { padding: 8px 12px; border-bottom: 1px solid var(--vf-light-border); }
  tbody tr:nth-child(even) { background-color: var(--vf-gray-bg); }
  blockquote {
    border-left: 4px solid var(--vf-teal); background-color: #f0f9fb;
    padding: 12px 16px; margin: 16px 0; border-radius: 0 6px 6px 0;
    font-size: 10pt; page-break-inside: avoid;
  }
  blockquote strong { color: var(--vf-navy); }
  code {
    background-color: var(--vf-gray-bg); padding: 2px 6px;
    border-radius: 3px; font-size: 9.5pt; color: var(--vf-navy);
  }
  pre {
    background-color: var(--vf-navy); color: #e0e0e0; padding: 16px;
    border-radius: 6px; font-size: 9pt; overflow-x: auto; page-break-inside: avoid;
  }
  pre code { background: none; color: inherit; padding: 0; }
  img {
    max-width: 100%; border: 1px solid var(--vf-light-border);
    border-radius: 6px; box-shadow: 0 2px 8px rgba(2, 48, 71, 0.1);
    margin: 16px 0; page-break-inside: avoid;
  }
  img + br + em, p > em:only-child {
    display: block; text-align: center; font-size: 9pt; color: #666;
    margin-top: -8px; margin-bottom: 16px;
  }
  a { color: var(--vf-blue); text-decoration: none; }
  a:hover { text-decoration: underline; }
  ul, ol { margin: 8px 0; padding-left: 24px; }
  li { margin-bottom: 4px; }
  li strong { color: var(--vf-navy); }
  hr { border: none; height: 2px; background: linear-gradient(90deg, var(--vf-teal), transparent); margin: 30px 0; }
  h2#table-of-contents + ol, h2 + ol {
    background: var(--vf-gray-bg); padding: 20px 20px 20px 40px;
    border-radius: 6px; border-left: 4px solid var(--vf-navy);
  }
  strong { font-weight: 600; }
  @media print {
    body { font-size: 10.5pt; }
    h1 { font-size: 24pt; }
    h2 { font-size: 16pt; }
    h3 { font-size: 12pt; }
    img { max-height: 400px; object-fit: contain; }
  }
---

<div class="cover-page">

<img src="../assets/velocity-logo.jpg" alt="Velocity Fibre Logo" />

<div class="cover-title">FibreFlow</div>
<div class="cover-subtitle">COMPLETE USER MANUAL</div>

<hr class="cover-divider" />

<div class="cover-meta">
<strong>Version:</strong> 1.3<br/>
<strong>Last Updated:</strong> 11 February 2026<br/>
<strong>Application:</strong> FibreFlow (fibreflow.app)<br/>
<strong>Scope:</strong> All Modules<br/>
<strong>Classification:</strong> Internal Use
</div>

<div class="cover-footer">
Velocity Fibre (Pty) Ltd — Connecting Communities, Empowering Futures
</div>

</div>

# FibreFlow — Complete User Manual

## Table of Contents

1. [Getting Started](#1-getting-started)
2. [Main — Dashboard, Meetings & Action Items](#2-main--dashboard-meetings--action-items)
3. [Project Management](#3-project-management)
4. [Activate — QA & Photo Review](#4-activate--qa--photo-review)
5. [Field Operations](#5-field-operations)
6. [Maintenance](#6-maintenance)
7. [Procurement](#7-procurement)
8. [Assets](#8-assets)
9. [Fleet Management](#9-fleet-management)
10. [Human Resources](#10-human-resources)
11. [Analytics](#11-analytics)
12. [Communications](#12-communications)
13. [System Administration](#13-system-administration)
14. [Appendices](#14-appendices)

---

## How to Use This Manual

This manual covers every module in FibreFlow, organized by the sidebar navigation sections. Each chapter includes:

- **Overview** — What the module does and who uses it
- **Navigation** — How to reach the module from the sidebar
- **Features** — Detailed walkthrough of each feature with screenshots
- **Workflows** — Step-by-step procedures for common tasks
- **Troubleshooting** — Solutions for common issues

**Conventions used in this manual:**

| Convention | Meaning |
|------------|---------|
| **Bold text** | UI element names (buttons, tabs, labels) |
| \`Code text\` | Technical values, field names, or system identifiers |
| > **Tip:** | Helpful shortcut or best practice |
| > **Important:** | Critical information — read carefully |
| *Italic text* | Figure captions below screenshots |

**Role Badges:** Where features are restricted by role, you will see tags like **(Admin only)** or **(Manager+)**.

---

## 1. Getting Started

### 1.1 Accessing FibreFlow

FibreFlow is a web application accessible from any modern browser (Chrome, Firefox, Edge, Safari).

| Environment | URL | Purpose |
|-------------|-----|---------|
| **Production** | app.fibreflow.app | Live system for daily use |
| **Staging** | vf.fibreflow.app | Pre-release testing |
| **Development** | dev.fibreflow.app | Feature development |

1. Open your browser and navigate to **app.fibreflow.app**
2. Enter your email address and password
3. Click **Sign In**
4. You will be redirected to the Dashboard

![Login Page](../screenshots/complete/01-login.png)
*Figure 1.1: FibreFlow login page*

> **Tip:** If you forget your password, contact your system administrator to reset it.

### 1.2 The FibreFlow Interface

After logging in, you will see the main interface consisting of:

- **Sidebar** (left) — Navigation menu organized into sections
- **Header** (top) — Search bar, notifications, user menu, dark mode toggle
- **Content Area** (center) — The active page content
- **Tabs** (within modules) — Horizontal tab navigation within each module

![Main Interface](../screenshots/complete/02-interface-overview.png)
*Figure 1.2: FibreFlow main interface showing sidebar, header, and content area*

### 1.3 Navigation Structure

The sidebar is organized into **12 sections**, each representing a major area of the application:

| Section | Icon | Purpose |
|---------|------|---------|
| **Main** | Home | Dashboard, Meetings, Action Items |
| **Project Management** | Folder | Projects, Clients, Contractors |
| **Activate** | CheckCircle | QA photo review and DR processing |
| **Field Operations** | CheckSquare | QField QA, field validation tools |
| **Maintenance** | Wrench | Maintenance ticket management |
| **Procurement** | ShoppingCart | BOQ, RFQ, PO, inventory |
| **Assets** | Package | Equipment and asset tracking |
| **Fleet** | Truck | Vehicle and driver management |
| **Human Resources** | Users | Staff directory and compliance |
| **Analytics** | BarChart | KPIs, reports, dashboards |
| **Communications** | MessageSquare | WhatsApp, meetings, notifications |
| **System** | Settings | Admin tools, data sync, settings |

Click a section header to expand or collapse it. Sections with a direct link (like Activate or Maintenance) navigate directly to that module.

### 1.4 User Roles & Permissions

FibreFlow uses Role-Based Access Control (RBAC). Your role determines which modules, pages, and actions you can access.

| Role | Description | Typical Access |
|------|-------------|---------------|
| **Super Admin** | Full system control | Everything — all modules, settings, system admin |
| **Admin** | Organization admin | All modules except system internals |
| **Manager** | Department/project lead | Projects, procurement, reports, team management |
| **Technician** | Field worker | Assigned tasks, check-ins, limited views |
| **Viewer** | Read-only observer | View dashboards and reports, no edit access |
| **Contractor** | External partner | Contractor portal, assigned project views |

> **Important:** If you cannot see a menu item or feature described in this manual, your role may not have access. Contact your administrator to request additional permissions.

#### Granular Tab-Level Permissions **(NEW)**

FibreFlow now supports **granular per-tab access control** within modules. This means:
- Different users can see different tabs within the same module
- Permissions are controlled at the individual tab level, not just module level
- Unauthorized tabs show a loading state briefly, then are hidden (no flash of unauthorized content)

Modules with tab-level permissions include:
- **System Data Sync** — Activate, QField, History, and OLT Report groups
- **Staff** — Per-tab access for Overview, Employment, Compliance, etc.
- **Access Control** — Instant client-side filtering with improved search UX

### 1.5 Common UI Patterns

FibreFlow uses consistent patterns across all modules:

**Search Bars** — Type to filter lists in real time. Most search bars filter across multiple fields (name, ID, description).

**Filters** — Dropdown or toggle filters to narrow results by status, date, category, or other criteria.

**Tab Navigation** — Horizontal tabs within modules let you switch between sub-sections without leaving the page.

**Modal Dialogs** — Forms and details often open in overlay modals. Click outside or press Escape to close.

**Toast Notifications** — Success/error messages appear briefly in the corner of the screen.

**Dark Mode** — Toggle dark mode from the header menu (user icon → Theme toggle). All modules support dark mode with consistent styling.

**Mobile Responsive Design** **(ENHANCED)** — FibreFlow is now optimized for mobile devices with:
- Scrollable tab navigation on smaller screens
- Responsive breakpoints across 28 updated files
- Stacked headers and improved touch targets
- Mobile-friendly data tables and forms

---

## 2. Main — Dashboard, Meetings & Action Items

### 2.1 Dashboard

The Dashboard is your landing page after login. It provides a high-level overview of your organization's operations.

**Navigation:** Sidebar → **Main** → **Dashboard** (or click the FibreFlow logo)

![Dashboard](../screenshots/complete/03-dashboard.png)
*Figure 2.1: Main Dashboard showing project overview cards, activity feed, and quick actions*

#### Statistics Cards

The top row displays key metrics:

| Card | Description |
|------|-------------|
| **Active Projects** | Number of currently active projects |
| **Total Staff** | Number of staff members in the system |
| **Open Tickets** | Maintenance tickets requiring attention |
| **Pending QA** | Activate reviews waiting for QA processing |

#### Project Overview

A grid of project cards showing each project's:
- Name and client
- Status (Active, Planning, On Hold, Completed)
- Progress percentage
- Key dates

#### Recent Activity Feed

A chronological stream of recent actions across the system — ticket updates, project changes, new submissions, and more.

#### Quick Actions

Shortcut buttons for common tasks:
- **Create Project** — Start a new project
- **Create Ticket** — Open a maintenance ticket
- **Import SOW** — Upload a Scope of Work document
- **View Reports** — Navigate to analytics

### 2.2 Meetings **(ENHANCED)**

The Meetings module integrates with Fireflies.ai to automatically sync meeting transcripts, summaries, and action items. Meetings are now **integrated into the Communications Portal**.

**Navigation:** Sidebar → **Communications** → **Communications Portal** → **Meetings** tab

![Meetings](../screenshots/complete/04-meetings.png)
*Figure 2.2: Meetings page showing synced transcripts with search and date filters*

#### Features

- **Auto-sync** — Meetings from Fireflies.ai are automatically synced to FibreFlow
- **Manual sync** — Click **Sync Now** to pull the latest transcripts
- **Participant-based Access** — Users only see meetings they attended
- **Super Admin Override** — Super admins can view all meetings
- **Meeting detail** — Click any meeting to view:
  - Full transcript
  - AI-generated summary with key points
  - Action items extracted from the meeting
  - Participants list
  - Duration and date

#### Enhanced Participant Tracking **(NEW)**

FibreFlow now uses improved participant matching for better accuracy:

- **Fireflies Speakers Data** — Uses speakers data from Fireflies for more accurate participant tracking
  - Identifies participants by their actual speaking contributions
  - Reduces false positives from attendees who didn't participate
  - Better handles multi-organization meetings

- **Enhanced Attendee Display** — Improved attendee list in Communications portal:
  - Clear distinction between active speakers and passive attendees
  - Accurate participant counts
  - Better handling of external attendees

- **Non-Admin User Matching** — Improved participant matching for non-admin users:
  - Uses name matching when email matching fails
  - Handles variations in name format (First Last, Last First, etc.)
  - More reliable access control for regular users

#### Meeting Detail Modal

| Section | Content |
|---------|---------|
| **Summary** | AI-generated meeting summary |
| **Keywords** | Key topics discussed |
| **Action Items** | Tasks identified from the conversation |
| **Outline** | Structured breakdown of the meeting |
| **Participants** | List of attendees with speaker identification |

> **Tip:** If you attended a meeting but it's not showing up, check that your name or email in FibreFlow matches what was recorded in Fireflies. Contact your administrator to update your profile if needed.

### 2.3 Action Items

Track tasks and follow-ups that come out of meetings, projects, or ad-hoc assignments.

**Navigation:** Sidebar → **Communications** → **Action Items**

![Action Items](../screenshots/complete/05-action-items.png)
*Figure 2.3: Action Items list with status filters and assignee tracking*

#### Features

- **Create** — Add new action items with title, description, assignee, and due date
- **Filter** — Filter by status (Open, In Progress, Completed) or assignee
- **Track** — Monitor progress with status updates and due date tracking
- **Link** — Action items can be linked to meetings or projects

---

## 3. Project Management

### 3.1 Projects List

The Projects module is the core of FibreFlow, managing fiber network deployment projects from planning through completion.

**Navigation:** Sidebar → **Project Management** → **Projects**

![Projects List](../screenshots/complete/06-projects-list.png)
*Figure 3.1: Projects list showing active projects with status, progress, and quick filters*

#### Views

- **Grid View** — Card-based layout showing project cards with key metrics
- **List View** — Table layout with sortable columns

#### Filters

| Filter | Options |
|--------|---------|
| **Status** | All, Active, Planning, On Hold, Completed |
| **Search** | Search by project name, code, or client |
| **Sort** | Name, Date Created, Status, Progress |

#### Creating a New Project

1. Click **+ New Project** (top-right)
2. Fill in the required fields:
   - **Project Name** — Descriptive name
   - **Client** — Select from client list
   - **Project Code** — Auto-generated or manual
   - **Status** — Default: Planning
   - **Start Date** and **Target End Date**
3. Click **Save**

### 3.2 Project Detail **(ENHANCED)**

Click any project to view its detail page with comprehensive tabs.

![Project Detail](../screenshots/complete/07-project-detail.png)
*Figure 3.2: Project detail page showing overview tab with team, timeline, and key metrics*

#### Tabs

| Tab | Content |
|-----|---------|
| **Overview** | Project info, KPI cards, workflow checklist, activation progress |
| **Team** | Assigned staff and contractors with roles |
| **Timeline** | Activity timeline and milestones |
| **SOW** | Scope of Work data with statistics cards and drop counts |
| **Documents** | Centralized file uploads for project documentation **(NEW)** |
| **Procurement** | BOQ, RFQ, PO summary for this project |
| **Health & Safety** | H&S compliance, incidents, checklists |
| **Wayleaves** | Wayleave applications and servitude agreements |
| **Reports** | Project-specific reports |

#### Overview Tab (Enhanced)

The Overview tab now includes:
- **KPI Cards** — Key metrics showing activation progress, completion rates, and blockers
- **Workflow Checklist** — Track project milestones and requirements
- **Progress from Activations** — Real-time progress calculated from actual OES activation data

#### Team Management

The Team tab shows a unified view of all team members (staff and contractors):
- **Primary Manager** — The project lead (marked with star icon)
- **Team Members** — Staff assigned to this project
- **Contractors** — External contractors working on the project
- Add/remove members using the **+ Add Member** button

#### Client PO Management **(NEW)**

Track purchase orders received from clients for project activations:
- **PDF Import** — Upload client PO documents (PDF) for automatic data extraction via VLM
- **VAT Breakdown** — Create modal shows VAT breakdown with net, VAT, and total amounts
- **Activation Requirements** — Link POs to activation seed requirements
- **Blockers Tracking** — Identify activation blockers based on PO status

#### Documents Tab **(NEW)**

The Documents tab provides centralized file storage for project documentation:
- **Upload and organize** — Project files with support for multiple file types (PDF, images, documents)
- **Secure HTTPS URLs** — All stored files accessible via secure links
- **VF Storage integration** — Uses flat folder structure for efficient storage
- **Access control** — Files accessible to project team members based on permissions

### 3.3 Pipeline

The Pipeline module tracks project progression through pre-construction phases — from initial proposal to construction readiness.

**Navigation:** Sidebar → **Project Management** → **Projects** → **Pipeline** tab

![Pipeline](../screenshots/complete/08-pipeline.png)
*Figure 3.3: Pipeline view showing projects across approval stages*

#### Sub-tabs

| Tab | Purpose |
|-----|---------|
| **Overview** | Pipeline stages and project positioning |
| **Authorities** | Service authority management and approvals |
| **Alerts** | Pipeline alerts and blockers |

#### Pipeline Stages

Projects move through defined stages:
1. **Proposal** — Initial project proposal
2. **Due Diligence** — Feasibility study and site surveys
3. **Approvals** — Municipal and authority approvals
4. **Design** — Network design and engineering
5. **Ready for Construction** — All approvals received

#### Authorities

Manage service authorities required for each project:
- Add authority requirements (municipal, environmental, utility)
- Track submission and approval status
- Upload supporting documents
- Set expiry dates

### 3.4 Execution & Progress

Track daily progress and manage project tasks during the construction phase.

**Navigation:** Sidebar → **Project Management** → **Projects** → **Execution** tab

#### Progress Reports

- View daily progress entries by project
- Track meters of fiber installed, poles erected, drops connected
- Compare planned vs actual progress

#### Tasks

- Create and assign project tasks
- Set priorities and due dates
- Track task completion status

### 3.5 Health & Safety

Manage health and safety compliance for each project.

**Navigation:** Sidebar → **Project Management** → **Projects** → **Health & Safety** tab

![Health & Safety](../screenshots/complete/09-health-safety.png)
*Figure 3.4: Health & Safety dashboard showing incident tracking and compliance scores*

#### Sub-tabs

| Tab | Purpose |
|-----|---------|
| **Dashboard** | H&S compliance overview and statistics |
| **Incidents** | Record and track safety incidents |
| **Checklists** | Safety inspection checklists |

#### Incident Management

- Record incidents with type, severity, date, and description
- Attach photos and documents
- Track investigation status and corrective actions
- View incident trends over time

### 3.6 Clients

Manage client organizations associated with your fiber projects.

**Navigation:** Sidebar → **Project Management** → **Clients**

![Clients](../screenshots/complete/10-clients.png)
*Figure 3.5: Clients list showing organization details and project counts*

#### Features

- **Client List** — View all clients with search and status filters
- **Client Detail** — Click to view full details including:
  - Contact information (name, phone, email, address)
  - Associated projects
  - Financial summary (total revenue)
  - Notes and communications history
- **Create Client** — Add new client organizations
- **Edit/Delete** — Manage existing client records

### 3.7 Contractors **(ENHANCED)**

Manage external contractors and their performance, including the new **Company Verification System**.

**Navigation:** Sidebar → **Project Management** → **Contractors**

#### Features

- **Contractor Portal** — List of all contractors with project assignments
- **RAG Dashboard** — Red/Amber/Green performance ratings:
  - **Red** — Significant issues, action required
  - **Amber** — Minor issues, monitor closely
  - **Green** — Performing well
- **Document Reports** — Track contractor document compliance (insurance, licenses, etc.)

#### Company Verification System **(NEW)**

FibreFlow now includes a comprehensive contractor verification system for onboarding:

**Verification Types:**
- **CIPC Company Verification** — Verify company registration and director details
- **SA ID Validation** — Validate South African ID numbers
- **ID Photo Verification** — Match ID photos to registered IDs
- **Criminal Record Checks** — Background criminal record verification
- **PEP & Sanctions** — Politically Exposed Persons and sanctions screening

**Verification Process:**
1. **Company Registration** — Upload CIPC certificate and verify against SearchWorks API
2. **Director Verification** — Validate all directors' ID numbers and match to CIPC records
3. **Individual Checks** — Perform background checks on key personnel
4. **Document Compliance** — Ensure all required documents are uploaded and valid
5. **Final Approval** — Complete verification before contractor activation

**Verification Bundles:**
- **Basic** — Essential CIPC and ID verification
- **Standard** — Includes criminal record checks
- **Enhanced** — Adds PEP/sanctions screening
- **Full Due Diligence** — Comprehensive verification package

### 3.8 Reports

Project-level reporting and analytics.

**Navigation:** Sidebar → **Project Management** → **Projects** → **Reports** tab

- Project progress reports
- Timeline adherence tracking
- Budget vs actual spending
- Resource utilization reports

---

## 4. Activate — QA & Photo Review

The Activate module is FibreFlow's AI-powered quality assurance system for verifying field installations through photo review.

### 4.1 Dashboard

**Navigation:** Sidebar → **Activate** (click section header)

![Activate Dashboard](../screenshots/complete/11-activate-dashboard.png)
*Figure 4.1: Activate Dashboard showing QA statistics, project filter, and drop counts by status*

#### Statistics Cards

| Card | Description |
|------|-------------|
| **Total DRs** | Total drop reference numbers in the system |
| **Pending QA** | DRs awaiting quality review |
| **Passed** | DRs that passed QA review |
| **Failed** | DRs that failed QA review |
| **Rework** | DRs sent back for corrections |

#### Project Filter

Select a specific project to filter the dashboard data, or view across all projects.

### 4.2 QA Centre

The QA Centre is the main workspace for reviewing field installation photos.

**Navigation:** Sidebar → **Activate** → **QA Centre** tab

![QA Centre](../screenshots/complete/12-activate-qa-centre.png)
*Figure 4.2: QA Centre showing DR list with status badges, search, and filter options*

#### DR List

A searchable, filterable list of all drop reference numbers (DRs):

| Column | Description |
|--------|-------------|
| **DR Number** | Unique drop reference (e.g., DR1738371) |
| **Project** | Associated project name |
| **Status** | QA status badge (Pending, Passed, Failed, Rework) |
| **Photos** | Number of photos available |
| **Submitted** | Date the DR was submitted for review |
| **Reviewed** | Date of last QA review |

#### Search & Filters

- **Search** — Find DRs by number, project, or installer name
- **Status Filter** — Pending, Passed, Failed, Rework, All
- **Project Filter** — Filter by specific project
- **Date Range** — Filter by submission date

### 4.3 QA Wizard — 5-Phase Review

Click any DR to open the QA Wizard — a guided 5-phase review process.

![QA Wizard](../screenshots/complete/13-activate-qa-wizard.png)
*Figure 4.3: QA Wizard showing the photo review phase with categorized installation photos*

#### Phase 1: Prerequisites

Validates that the DR has sufficient data for review:
- Minimum photo count met
- Photos have been AI-categorized
- OES data available
- Contact information present

#### Phase 2: Photo Review

Review installation photos mapped to a 10-step checklist:

| Step | Label | What to Check |
|------|-------|---------------|
| 1 | House Photo | Property correctly identified |
| 2 | Cable from Pole | Cable routed properly from pole |
| 3 | Entry Outside | External cable entry point |
| 4 | Entry Inside | Internal cable entry point |
| 5 | Wall | Wall mount installation |
| 6 | ONT Back | ONT device installed correctly |
| 7 | Power Meter | Signal strength reading (-18 to -24 dBm) |
| 8 | Final Installation | Completed installation overview |
| 9 | Green Lights | ONT LED indicators showing green |
| 10 | Signature | Customer sign-off obtained |

For each step:
- View the assigned photo(s)
- Approve or flag issues
- Re-assign photos to different steps if AI categorization was incorrect

#### Phase 3: Data Validation **(ENHANCED)**

Validates extracted data with enhanced duplicate detection:

- **Power meter reading** — Must be between -18 and -24 dBm
- **ONT serial** — Extracted serial matches expected format (ALCL prefix)
- **DR number** — Matches the submission

**Duplicate Serial Detection (NEW):**

The system now performs comprehensive serial validation during DR acknowledgment:

- **Duplicate Detection** — Automatically detects when an ONT or UPS serial is already used on another DR
  - Displays bold warning with 🔴 formatting
  - Names the conflicting DR number (e.g., "Already used on DR1234567")
  - Prevents accidental duplicate activations

- **Serial Mismatch Warnings** — Compares 1Map data to sticker photo readings:
  - 🔴 **Bold red warnings** when serials don't match between sources
  - Helps identify data entry errors or incorrect equipment
  - Flags discrepancies for immediate resolution

- **Missing Serial Prompts** — Clear indicators for incomplete data:
  - **"NOT SCANNED"** labels shown when serial is missing from photos
  - Prompts technician to capture required serial photos
  - Prevents QA approval until all serials are validated

- **Real-Time Validation** — All checks run automatically during DR acknowledgment workflow
  - No manual checking required
  - Immediate feedback to QA reviewer
  - Reduces activation errors and rework

> **Tip:** When you see a duplicate serial warning, investigate immediately. The serial may have been entered incorrectly, or equipment may have been swapped between installations.

#### Phase 4: Final Decision

Make the QA decision:

| Decision | Action | Result |
|----------|--------|--------|
| **Pass** | Installation meets all requirements | DR marked as approved |
| **Fail** | Critical issues found | DR marked as failed with reason codes |
| **Rework Needed** | Minor issues to fix | DR sent back to installer with feedback |

Select a reason code when failing or requesting rework:
- Missing photos
- Poor photo quality
- Installation defect
- Serial mismatch
- Signal out of range

#### Phase 5: Feedback

Generate and send feedback to the field installer:
- Auto-generated feedback message based on decision and reason codes
- Sent via WhatsApp to the installer
- Includes specific issues to address
- Tracks acknowledgment status

### 4.4 PP Data Management **(ENHANCED)**

PP Data (Pre-Provisioned ONT Data) manages ONTs that are pre-registered in the system before activation.

**Navigation:** Sidebar → **Activate** → **PP Data** tab

#### Features

- **Auto-Import** — PP Data is automatically extracted from OES Excel file imports (PP DATA sheet)
- **Enhanced Resolution** — Match pre-provisioned ONT serials to actual installations via:
  - **Local Scan (12 Sources)** — Expanded from 3 to **12 local data sources** for comprehensive serial matching:
    - OES activation records
    - DR submissions
    - Photo review data
    - 1Map sync records
    - QField captures
    - Maintenance tickets
    - PP Data imports
    - OLT reports
    - Historical activations
    - Cross-project matches
    - UPS serial tracking
    - Serial correction logs
  - **1Map Lookup** — Bulk lookup against 1Map API for drop assignments
  - **Live Progress Tracking** — Real-time progress indicators during 1Map serial lookups:
    - Progress bar showing current/total lookups
    - Percentage completion
    - Estimated time remaining
    - Success/failure counts during processing

- **Status Tracking** — Track resolution status:
  - **Unresolved** — Serial not yet matched to a drop
  - **OES Match** — Matched via OES activation data
  - **Unified Match** — Matched via unified data sources
  - **OneMap Match** — Matched via OneMap API
  - **1Map Match** — Matched via 1Map direct lookup

#### Summary Statistics

Dashboard cards show:
- **Total Imported** — All PP Data records imported
- **Resolved** — Successfully matched to drops
- **Unresolved** — Still awaiting resolution
- **Last Import** — Most recent import date and file details

#### Excel Export **(NEW)**

Export PP Data with project and status filters:
- Apply project and status filters
- Click **Export Excel** to download filtered data
- Includes all resolution details and timestamps

#### Create Maintenance Tickets **(NEW)**

Unresolved PP Data records can now be converted directly into maintenance tickets:

1. Navigate to the **PP Data** tab
2. Filter to show **Unresolved** records
3. Select records that require investigation
4. Click **Create Maintenance Ticket**
5. The system creates a ticket with:
   - Serial number details
   - Project context
   - PP Data import information
   - Priority level based on age of record
6. Technicians can investigate and resolve the discrepancy

> **Tip:** Use the expanded local data sources to resolve more PP Data records without relying on 1Map lookups. The system now checks 12 different sources automatically before marking a record as unresolved.

### 4.5 VLM AI Integration

FibreFlow uses a Vision Language Model (VLM) — Qwen3-VL — to automatically process installation photos:

- **Auto-categorization** — Photos are categorized to the 10-step checklist
- **Serial Extraction** — ONT serial numbers are read from photos
- **Power Reading** — dBm values extracted from power meter photos
- **DR Detection** — DR numbers identified from labels

> **Tip:** AI categorization is a starting point — always verify and correct during the Photo Review phase. Your corrections are saved and improve future AI accuracy through few-shot learning.

### 4.6 Reports

**Navigation:** Sidebar → **Activate** → **Reports** tab

![Activate Reports](../screenshots/complete/14-activate-reports.png)
*Figure 4.4: Activate Reports dashboard showing trend analysis and performance metrics*

Available report types:

| Report | Description |
|--------|-------------|
| **Trends** | QA pass/fail rates over time |
| **Funnel** | DR progression through QA stages |
| **Team Performance** | Reviewer throughput and accuracy |
| **Serial Validation** | ONT serial match rates |
| **Offline Devices** | Installations with connectivity issues |
| **Serial Mismatch** | DRs where serial numbers do not match expected |
| **Installation Gaps** | Missing checklist steps |
| **Anomaly Detection** | Unusual patterns in submissions |

All reports support:
- Date range filtering
- Project filtering
- CSV export

### 4.7 OES Import & Data Sync

**(Admin only)**

- **OES Import** — Import OES (Operation Engineering Support) activation data from Excel files
- **SharePoint Sync** — Synchronize DR data from SharePoint document libraries
- **QField Sync** — Push OES coordinate data to QField for field mapping

---

## 5. Field Operations **(NEW SECTION)**

The Field Operations section provides specialized tools for field workers and QA supervisors to validate and manage field-captured data.

### 5.1 QField QA **(NEW)**

QField QA is a comprehensive photo validation and quality assurance system for field-captured photos from the QField mobile GIS application.

**Navigation:** Sidebar → **Field Operations** → **QField QA**

![QField QA Dashboard](../screenshots/complete/15-qfield-qa-dashboard.png)
*Figure 5.1: QField QA Dashboard showing validation statistics and photo queue*

#### Overview Tab

The dashboard provides comprehensive statistics:

| Metric | Description |
|--------|-------------|
| **Total Photos** | All photos imported from QField |
| **Validated** | Photos that have passed AI or human validation |
| **Rejected** | Photos requiring retakes |
| **In Review** | Photos assigned to reviewers |
| **Pending** | Photos awaiting validation |

#### Photo Validation Workflow

**AI-Powered Validation:**
- **VLM Integration** — Uses Qwen3-VL Vision Language Model for automatic photo analysis
- **Real-time Feedback** — AI provides immediate feedback on photo quality and compliance
- **Confidence Scoring** — Each validation includes a confidence score (0-100%)
- **Issue Detection** — Automatic identification of common problems:
  - Poor lighting or blur
  - Missing equipment or installations
  - Safety compliance issues
  - Incomplete work documentation

**Human Review Process:**
1. **Assignment** — Photos can be assigned to specific reviewers
2. **Bulk Actions** — Process multiple photos simultaneously
3. **Approval/Rejection** — Final human decision overrides AI recommendations
4. **Escalation** — Complex cases can be escalated to supervisors
5. **WhatsApp Notifications** — Automatic notifications sent to field teams about rejections

#### My Queue Tab **(ENHANCED)**

Personalized queue for assigned reviewers:
- **Assigned Photos** — Photos specifically assigned to the current user
- **Priority Filters** — Sort by priority level (Low, Medium, High, Urgent)
- **Due Date Tracking** — Visual indicators for approaching deadlines
- **Quick Actions** — Approve, reject, or request more info with one click

#### All Photos Tab **(ENHANCED)**

System-wide photo management:
- **Comprehensive Search** — Search by project, pole number, work type, or status
- **Advanced Filters** — Filter by validation status, confidence score, date range
- **Enhanced Bulk Assignment** — Assign multiple photos to reviewers with:
  - **Due Date Selection** — Set due dates for assigned photos
  - **Priority Levels** — Choose priority (Low, Medium, High, Urgent) for assignments
  - **Batch Processing** — Assign multiple photos simultaneously with same criteria
  - **Assignment Preview** — Review assignments before confirming
- **Pole Number Mapping** — Photos linked to specific pole locations for geographic context:
  - **Enhanced Pole Display** — Improved pole number visibility on photo cards
  - **Photo-to-Pole Association** — Automatic mapping of photos to pole numbers from QField data
  - **Geographic Context** — View pole locations on project maps
  - **Pole-Based Filtering** — Filter photos by specific pole numbers for targeted review

#### Photo Detail Modal

Enhanced photo review interface:
- **Full Resolution Display** — High-quality photo viewing with zoom capabilities
- **AI Analysis Results** — Detailed VLM feedback and recommendations
- **Validation History** — Track all review actions and decisions
- **Geographic Context** — Show pole numbers and project location data
- **Action Buttons** — Approve, reject, escalate, or reassign with comments

#### QField Plugin Integration **(NEW)**

FibreFlow provides a **real-time validation plugin for QField**:
- **Instant Feedback** — Photos validated immediately upon capture in QField
- **Offline Capability** — Cache validations for sync when connection available
- **Quality Guidance** — Real-time tips for improving photo quality
- **Compliance Checks** — Automatic verification against work standards

> **Important:** The QField plugin requires proper authentication setup and QField version compatibility. Contact your system administrator for plugin installation.

### 5.2 Photo Validation API

The QField QA system includes RESTful APIs for integration:

| Endpoint | Method | Purpose |
|----------|--------|---------|
| \`/api/qfield/qa-validations\` | GET | Retrieve photo list with filters |
| \`/api/qfield/qa-validate\` | POST | Trigger VLM validation |
| \`/api/qfield/qa-actions\` | POST | Approve/reject photos |
| \`/api/qfield/qa-assignments\` | POST | Assign photos to reviewers |
| \`/api/qfield/qa-stats\` | GET | Dashboard statistics |

### 5.3 Integration with Other Modules

QField QA integrates seamlessly with other FibreFlow modules:
- **Projects** — Photos linked to specific project phases
- **Maintenance** — Maintenance photos validated through same workflow
- **Communications** — WhatsApp notifications for rejected photos
- **Analytics** — Quality metrics included in reporting dashboards

---

## 6. Maintenance

The Maintenance module manages the complete lifecycle of fiber network maintenance tickets.

> **Note:** A comprehensive standalone Maintenance manual is available with detailed coverage of all features. This chapter provides an overview — see the dedicated **FibreFlow Maintenance Module User Manual** for in-depth documentation.

### 6.1 Dashboard

**Navigation:** Sidebar → **Maintenance** (click section header)

![Maintenance Dashboard](../screenshots/complete/16-maintenance-dashboard.png)
*Figure 6.1: Maintenance Dashboard showing ticket statistics, SLA compliance, and workload*

#### Key Metrics

| Metric | Description |
|--------|-------------|
| **Total Tickets** | All maintenance tickets |
| **Open** | Tickets awaiting action |
| **Overdue** | Tickets exceeding SLA target |
| **Avg. Resolution** | Average resolution time |
| **SLA Compliance** | Percentage meeting response targets |

### 6.2 Work Orders — Kanban Board

The primary ticket management view with drag-and-drop columns.

**Navigation:** Sidebar → **Maintenance** → **Work Orders** tab

![Kanban Board](../screenshots/complete/17-maintenance-kanban.png)
*Figure 6.2: Maintenance Kanban Board with tickets organized by status columns*

#### Columns

| Column | Description |
|--------|-------------|
| **New** | Newly created tickets |
| **Triaged** | Assessed and categorized |
| **Assigned** | Assigned to a technician |
| **In Progress** | Work actively underway |
| **Blocked** | Blocked by an external issue |
| **Resolved** | Work completed |
| **Closed** | Ticket fully closed |

#### Ticket Lifecycle

\`\`\`
NEW → ASSIGNED → IN_PROGRESS → PENDING_QA → QA_APPROVED → CLOSED
                                    ↓
                              QA_REJECTED → back to IN_PROGRESS
\`\`\`

### 6.3 Key Features Summary

| Feature | Description | See Standalone Manual Section |
|---------|-------------|-------------------------------|
| **Ticket Creation** | Create tickets manually or via import | Section 6 |
| **Team Management** | Organize internal and contractor teams | Section 8 |
| **QContact Sync** | Bidirectional sync with FiberTime QContact CRM | Section 9 |
| **Escalations** | Automatic repeat fault detection | Section 10 |
| **Handover** | 5-gate controlled team transitions | Section 11 |
| **Risk Acceptance** | Conditional QA approvals | Section 12 |

### 6.4 SLA Targets

| Priority | SLA Target |
|----------|-----------|
| Critical | 6 hours |
| Urgent | 12 hours |
| High | 1 day |
| Normal | 3 days |
| Low | 7 days |

### 6.5 Fault Cause Attribution

Every maintenance ticket requires a fault cause — this determines contractor liability:

| Fault Cause | Contractor Liable? |
|-------------|-------------------|
| **Workmanship** | YES |
| **Material Failure** | No |
| **Client Damage** | No |
| **Third Party** | No |
| **Environmental** | No |
| **Vandalism** | No |
| **Unknown** | No |

> **Important:** Fault cause selection directly affects contractor billing. Choose accurately.

---

## 7. Procurement

The Procurement module manages the complete purchasing workflow — from Bill of Quantities through to goods receipt.

### 7.1 Dashboard

**Navigation:** Sidebar → **Procurement** (click section header)

![Procurement Dashboard](../screenshots/complete/18-procurement-dashboard.png)
*Figure 7.1: Procurement Dashboard showing order statistics, pending approvals, and quick actions*

#### Quick Actions

- **Create BOQ** — Start a new Bill of Quantities
- **New RFQ** — Create a Request for Quotation
- **Create PO** — Generate a Purchase Order
- **View Approvals** — Check pending approval items

#### Dashboard Tabs

The procurement module uses horizontal tabs for navigation:

| Tab | Purpose |
|-----|---------|
| **Dashboard** | Overview statistics and quick actions |
| **Sourcing** | BOQ management |
| **Purchasing** | RFQ and PO management |
| **Inventory** | Stock items, movements, stock takes |
| **Financial** | Cost tracking and budget overview |
| **Approvals** | Pending approval items |

### 7.2 Sourcing — BOQ Management

The Bill of Quantities (BOQ) manages material requirements for projects.

**Navigation:** Procurement → **Sourcing** tab

![BOQ List](../screenshots/complete/19-procurement-boq.png)
*Figure 7.2: BOQ management showing project BOQs with upload and column mapping features*

#### Creating a BOQ

1. Click **+ Create BOQ**
2. Select the **Project**
3. **Upload Excel file** — The system auto-detects columns:
   - Item description
   - Quantity
   - Unit of measure
   - Unit price
4. **Column Mapping** — Review and adjust detected columns
5. **Stock Matching** — System matches BOQ items to existing stock items using fuzzy matching
6. Review and **Confirm Import**

#### BOQ Features

- **Upload** — Import from Excel with auto-detection
- **Column Mapper** — Visual interface to map Excel columns to BOQ fields
- **Stock Matcher** — Fuzzy matching to link BOQ items to inventory
- **History** — Track BOQ revisions and changes
- **Export** — Download BOQ as Excel

### 7.3 RFQ — Request for Quotation

Send requests for quotation to suppliers and compare responses.

**Navigation:** Procurement → **Purchasing** tab → RFQ section

![RFQ Detail](../screenshots/complete/20-procurement-rfq.png)
*Figure 7.3: RFQ detail page showing line items, supplier responses, and comparison view*

#### Creating an RFQ

1. Navigate to **Purchasing** tab
2. Click **+ New RFQ**
3. Fill in:
   - **Title** — RFQ description
   - **Project** — Associated project
   - **Due Date** — Response deadline
   - **Items** — Add line items (from BOQ or manual entry)
4. Select **Suppliers** to send to
5. Click **Create & Send**

#### Managing RFQ Responses

- View responses from each supplier
- Compare prices side-by-side
- Select winning quotes
- **Convert to PO** — Create a purchase order from the selected response

### 7.4 Purchase Orders **(ENHANCED)**

Create and manage purchase orders with approval workflows.

**Navigation:** Procurement → **Purchasing** tab → PO section

![Purchase Order](../screenshots/complete/21-procurement-po.png)
*Figure 7.4: Purchase Order detail showing line items, approval status, and version history*

#### PO Approval Workflow

Purchase orders follow an approval chain based on value thresholds:

| Value Range | Required Approval |
|-------------|------------------|
| R0 – R10,000 | Manager approval |
| R10,001 – R50,000 | Senior manager + Director |
| R50,001+ | Executive approval |

#### PO Statuses

| Status | Description |
|--------|-------------|
| **Draft** | PO being prepared |
| **Pending Approval** | Awaiting approver sign-off |
| **Approved** | Ready to send to supplier |
| **Sent** | Sent to supplier |
| **Partially Received** | Some items received |
| **Fully Received** | All items received |
| **Cancelled** | PO cancelled |

#### PO Versioning

When a PO is modified after approval, a new version is created. The version history tracks all changes with timestamps and reasons.

#### VLM Learning Integration **(NEW)**

FibreFlow now includes VLM learning for Purchase Order extraction:
- **PDF Import** — Upload supplier PO documents for automatic data extraction
- **Learning System** — Human corrections improve future extraction accuracy
- **Confidence Scoring** — Each extraction includes a confidence score
- **Manual Override** — Users can correct and improve AI extraction results

### 7.5 Inventory

Manage stock items, track movements, and perform stock takes.

**Navigation:** Procurement → **Inventory** tab

![Stock Management](../screenshots/complete/22-procurement-stock.png)
*Figure 7.5: Stock management dashboard showing items, levels, and movement history*

#### Stock Items

- View all stock items with search and category filters
- Visual stock level bars showing quantity vs max capacity
- Quick filters for **Low Stock** and **Out of Stock**
- Color-coded status indicators:
  - **Green** — Adequate stock
  - **Yellow** — Low stock (below minimum)
  - **Red** — Out of stock

#### Stock Movements

Track all inventory movements:
- **Receipts** — Items received from suppliers (GRN)
- **Issues** — Items issued to projects
- **Transfers** — Items moved between locations
- **Adjustments** — Stock count corrections

#### Goods Receipt Notes (GRN)

Record received goods against purchase orders:
1. Navigate to a PO → Click **Receive Goods**
2. Enter quantities received for each line item
3. Note any discrepancies
4. Upload delivery note/photo
5. Confirm receipt

### 7.6 Financial **(ENHANCED)**

Cost tracking and budget overview for procurement activities.

**Navigation:** Procurement → **Financial** tab

- Total spend by project, supplier, and category
- Budget vs actual comparison
- Outstanding payment tracking
- Cost trends over time

#### Income Dashboard **(ENHANCED)**

The Income Dashboard now shows revenue tracking based on actual activations:
- **OES Activations** — Live activation counts from OES data
- **Revenue by Project** — Income breakdown per project based on actual completions
- **Client PO Status** — Outstanding and fulfilled client purchase orders
- **Real-time Progress** — Progress calculated from live activation data, not estimates

### 7.7 Approvals

View and action pending approvals across procurement.

**Navigation:** Procurement → **Approvals** tab

| Action | Description |
|--------|-------------|
| **Approve** | Approve the purchase order |
| **Reject** | Reject with reason |
| **Request Changes** | Send back for modifications |

### 7.8 Suppliers

Manage supplier relationships and item codes.

**Navigation:** (Accessed via Projects → Contractors or Procurement pages)

- **Supplier List** — All registered suppliers
- **Supplier Detail** — Contact info, item codes, performance
- **Item Codes** — Map supplier-specific codes to stock items
- **Performance** — On-time delivery, quality, pricing metrics

---

## 8. Assets

The Assets module provides complete asset lifecycle management for tools, equipment, and materials.

### 8.1 Dashboard

**Navigation:** Sidebar → **Assets** (click section header)

![Assets Dashboard](../screenshots/complete/23-assets-dashboard.png)
*Figure 8.1: Assets Dashboard showing total assets, available, assigned, and maintenance alerts*

#### Statistics Cards

| Card | Description |
|------|-------------|
| **Total Assets** | Total registered assets |
| **Available** | Assets ready for checkout |
| **Assigned** | Assets currently checked out |
| **In Maintenance** | Assets under repair/service |
| **Calibration Due** | Assets needing calibration |
| **Calibration Overdue** | Assets past calibration date |

### 8.2 All Assets

**Navigation:** Assets → **All Assets** tab

![Assets List](../screenshots/complete/24-assets-list.png)
*Figure 8.2: Assets list with search, category filter, and status indicators*

#### Viewing Assets

A searchable table of all assets with:
- **Asset Number** — Unique identifier
- **Name** — Asset description
- **Category** — Classification (Tools, Electronics, Vehicles, etc.)
- **Status** — Available, Assigned, In Maintenance, Retired
- **Location** — Current location or assigned person
- **Last Calibration** — Date of last calibration check

#### Creating an Asset

1. Click **+ New Asset**
2. Fill in required fields:
   - **Name** — Asset description
   - **Category** — Select from categories
   - **Asset Number** — Auto-generated or manual
   - **Serial Number** — Manufacturer serial
   - **Purchase Date** and **Purchase Price**
   - **Location** — Storage location
3. Optionally add:
   - **Barcode** — For QR code scanning
   - **Warranty Expiry** — Warranty end date
   - **Calibration Interval** — Days between calibrations
4. Click **Save**

### 8.3 Asset Detail

Click any asset to view its full detail page:

- **Overview** — All asset information
- **Documents** — Upload and manage asset documents (manuals, certificates)
- **Maintenance History** — Past and scheduled maintenance records
- **Assignment History** — Who has checked this asset out and when
- **Verification** — VLM-powered label verification (scan asset label to verify match)

### 8.4 Categories

**Navigation:** Assets → **Categories** tab

- Create and manage asset categories (e.g., Power Tools, Fiber Optic Equipment, Safety Gear)
- Each category can have custom fields

### 8.5 Check Out / Check In

**Navigation:** Assets → **Check Out / In** tab

#### Checking Out an Asset

1. Navigate to the asset or use **Check Out / In** tab
2. Click **Check Out**
3. Select the **Person** receiving the asset
4. Add **Purpose** and **Expected Return Date**
5. Confirm

#### Checking In an Asset

1. Find the checked-out asset
2. Click **Check In**
3. Note the **Condition** on return
4. Add any **Notes** about damage or issues
5. Confirm

### 8.6 Maintenance Scheduling

**Navigation:** Assets → **Maintenance** tab

- Schedule preventive maintenance
- Track maintenance history
- Set recurring maintenance intervals
- View upcoming and overdue maintenance

### 8.7 Calibration Tracking

**Navigation:** Assets → **Calibration** tab

- View assets with upcoming or overdue calibration
- Record calibration results
- Upload calibration certificates
- Set calibration intervals per asset

> **Important:** Overdue calibrations are flagged prominently on the dashboard. Using uncalibrated equipment may violate compliance requirements.

---

## 9. Fleet Management

The Fleet module manages vehicles, drivers, fuel, GPS tracking, and daily check-ins with AI-powered features.

### 9.1 Dashboard

**Navigation:** Sidebar → **Fleet** (click section header)

![Fleet Dashboard](../screenshots/complete/25-fleet-dashboard.png)
*Figure 9.1: Fleet Dashboard showing vehicle count, fuel spend, maintenance alerts, and driver stats*

### 9.2 Vehicles **(ENHANCED)**

**Navigation:** Fleet → **Vehicles** tab (now the default first tab)

![Vehicles List](../screenshots/complete/26-fleet-vehicles.png)
*Figure 9.2: Fleet vehicles list showing registration, make, driver assignment, and status*

#### Key Changes

- **Default View** — Vehicles tab is now the first tab (moved from second position)
- **Active Filter** — List defaults to showing only **Active** vehicles
- **Filtered Count** — Shows count of visible vehicles (e.g., "Showing 12 of 15 vehicles")
- **Enhanced License Disc Management** — Improved OCR verification workflow

#### Vehicle Information

Each vehicle record includes:
- Registration number and VIN
- Make, model, and year
- Assigned driver
- Current mileage
- Fuel level
- Service due date
- Insurance and license disc expiry
- Documents (registration, insurance, license disc, etc.)

#### License Disc Management **(ENHANCED)**

The license disc card now shows:
- **Expiry Date** — When the license disc expires (not issue date)
- **OCR Verification** — Upload a license disc photo for AI-powered data extraction:
  - Registration number verification
  - Expiry date extraction
  - Vehicle details confirmation
- **Full OCR Modal** — Complete verification workflow with extracted data preview and manual override options

### 9.3 Drivers

**Navigation:** Fleet → **Drivers** tab (now second tab)

- **Driver List** — All registered drivers with license status
- **Driver Detail** — Contact info, assigned vehicle, license details
- **Documents** — Upload and track:
  - Driver's license (front and back)
  - PrDP (Professional Driving Permit)
  - Medical certificate
- **License Expiry Alerts** — System warns when licenses are expiring

### 9.4 Vehicle Check-In **(ENHANCED)**

The daily/weekly vehicle inspection system with VLM-powered features and manager visibility.

**Navigation:** Fleet → **Check-In Audit** tab (or via Fleet Portal)

#### Key Enhancements

- **Manager Visibility** — Managers can now view **all check-in records** (not just their own)
- **Admin Controls** — Administrators can delete check-in records if needed
- **Fuel Level Integration** — Fuel levels from check-ins are now stored in the database
- **GPS Capture** — Check-ins now capture GPS coordinates for location tracking

#### Check-In Process

1. **Plate Scan** — The driver photographs the vehicle license plate
2. **VLM Verification** — AI reads the plate and verifies it matches the assigned vehicle
3. **GPS Capture** — System captures current GPS coordinates
4. **First-Time Calibration** (new vehicles only):
   - Enter current odometer reading
   - Select current fuel level (0-100%)
   - Upload dashboard photo
5. **Inspection Checklist** — Complete the inspection items:
   - Tire condition
   - Lights and indicators
   - Fluid levels
   - Body damage
   - Interior cleanliness
6. **Dashboard Reading** — VLM reads the dashboard photo to extract:
   - Odometer reading
   - Fuel level
   - Warning lights
7. **Photos** — Upload photos of any issues found
8. **Submit** — Complete the check-in

> **Tip:** The VLM (AI) reads license plates and dashboard displays automatically. However, always verify the readings are correct before submitting.

### 9.5 Fuel Management **(ENHANCED)**

**Navigation:** Fleet → **Fuel** tab

#### New Features

- **Fuel Gauge Photo Scanning (NEW)** — VLM-powered automatic fuel level detection:
  - **Dashboard Photo Capture** — Upload a photo of the vehicle dashboard during fuel fill-up
  - **AI Fuel Extraction** — VLM automatically reads fuel gauge percentage from the dashboard photo
  - **Visual Verification** — Review extracted fuel level before confirming
  - **Manual Override** — Adjust AI reading if needed for accuracy
  - **Integrated Workflow** — Fuel gauge reading captured alongside odometer during fill-up

- **Odometer Photo Capture** — VLM extraction of odometer readings from photos during fuel fill-up
- **Admin Delete** — Administrators can delete fuel transactions
- **Recalculated L/100km** — Fuel efficiency automatically recalculated after transaction changes
- **Receipt Scanning** — Enhanced receipt photo scanning with better error handling
- **Tank Level Integration** — Fuel level field added to portal fuel fill-up form

#### Features

- **Fuel Transactions** — Record fuel purchases with receipt scanning
- **Fuel Summary** — Total fuel spend by vehicle, driver, and period
- **Anomaly Detection** — System flags unusual fuel consumption patterns based on:
  - Fuel gauge readings vs. liters filled
  - Expected vs. actual consumption rates
  - Unusual fill-up patterns
- **Fuel Level Tracking** — Historical fuel levels from:
  - Check-in data
  - Fuel gauge photo scans
  - Manual entries

#### Fuel Fill-Up Process with Gauge Scanning

1. Navigate to **Fleet Portal** or **Fuel** tab
2. Click **Record Fuel Fill-Up**
3. Upload **Dashboard Photo** (showing fuel gauge and odometer)
4. VLM automatically extracts:
   - **Fuel Gauge Level** — Current tank level percentage (0-100%)
   - **Odometer Reading** — Current vehicle mileage
5. Review and adjust extracted values if needed
6. Upload **Receipt Photo** for cost scanning
7. Enter or verify:
   - Liters filled
   - Cost per liter
   - Total cost
8. Submit transaction

> **Tip:** Take dashboard photos from directly in front of the gauge for best AI accuracy. Ensure the fuel gauge needle and odometer numbers are clearly visible and well-lit.

### 9.6 Fleet Maintenance

**Navigation:** Fleet → **Maintenance** tab

- Schedule vehicle service and maintenance
- Track service history
- Set recurring maintenance intervals (km-based or time-based)
- View upcoming and overdue service items
- Manage service providers and costs

### 9.7 GPS Investigation

**Navigation:** Fleet → **GPS Investigation** tab

- **Upload GPS Data** — Import CSV files from GPS tracking devices
- **Trip Analysis** — View individual trips with routes, stops, and speeds
- **Anomaly Detection** — Flag unauthorized trips, excessive speed, or unusual routes
- **Driver Scorecards** — Performance ratings based on driving behavior

### 9.8 Check-In History & Locations **(ENHANCED)**

**Navigation:** Fleet → **Check-In History** / **Locations** tabs

#### Check-In History **(NEW TAB)**

- **Comprehensive History** — View all vehicle check-ins with timestamps
- **Photos Integration** — Access to check-in photos and documentation
- **Search & Filter** — Filter by vehicle, driver, date range, or status
- **Manager Access** — Full visibility for fleet managers

#### Locations & Portal

- **Locations** — Manage depot and parking locations
- **Portal** — Self-service driver portal for check-ins and reporting

---

## 10. Human Resources

The Human Resources module manages staff information, departments, compliance, and organizational structure.

### 10.1 Staff Directory **(ENHANCED)**

**Navigation:** Sidebar → **Human Resources** (click section header)

![Staff Directory](../screenshots/complete/27-staff-directory.png)
*Figure 10.1: Staff Directory showing employee list with search, department filter, and status*

#### Key Enhancements

- **Simplified Creation** — Staff creation now requires only name, email, and phone
- **Auto-Generated Employee ID** — Employee IDs are automatically generated
- **Granular Tab-Level Access Control** — Different users see different tabs based on permissions

#### Features

- **Search** — Find staff by name, email, or employee number
- **Filters** — Filter by department, position, status (active/inactive)
- **Grid/List View** — Toggle between card and table layouts
- **Quick Actions** — Add new staff member, export list

#### Creating Staff **(SIMPLIFIED)**

Creating a new staff member is now streamlined:

1. Click **+ New Staff Member**
2. Enter **required fields only**:
   - **First Name** — Staff member's first name
   - **Last Name** — Staff member's surname
   - **Email** — Work email address
   - **Phone** — Contact phone number
3. **Employee ID** — Automatically generated by the system
4. Click **Save**

Additional details (position, department, salary, etc.) can be added later via the edit form.

### 10.2 Staff Detail **(ENHANCED)**

Click any staff member to view their full profile with granular tab access:

![Staff Detail](../screenshots/complete/28-staff-detail.png)
*Figure 10.2: Staff detail page showing personal info, employment details, and compliance status*

#### Granular Tab-Level Permissions **(NEW)**

The staff detail page now supports per-tab access control:
- Users only see tabs they have permission to access
- Unauthorized tabs are hidden (no flash of unauthorized content)
- Loading spinner appears while permissions are checked

#### Tabs (Permission-Based)

| Tab | Content | Typical Access |
|-----|---------|---------------|
| **Overview** | Personal info, contact, address, identity documents | All users |
| **Employment** | Position, department, start date, reporting line | HR, Managers |
| **Compliance** | Document status, training records, certifications | HR only |
| **Notes** | Internal notes and communications log | HR, Supervisors |
| **Projects** | Projects this staff member is assigned to | Project managers |

#### Editing Staff

1. Click **Edit** on the staff detail page
2. The edit form has three sections:
   - **Overview** — Personal info, contact details, next of kin
   - **Employment** — Position, department, salary, contract type
   - **Compliance** — Document uploads and status tracking
3. Make changes and click **Save**

### 10.3 Departments

**Navigation:** Human Resources → **Departments** tab

![Departments](../screenshots/complete/29-departments.png)
*Figure 10.3: Departments grid showing department cards with member counts and status*

- View all departments as cards with member count
- Create new departments
- Edit department details
- View department reports (headcount, growth trends)

### 10.4 Alerts & Birthdays

**Navigation:** Human Resources → **Alerts** / **Birthdays** tabs

- **Alerts** — Expiring documents, overdue compliance items, license renewals
- **Birthdays** — Upcoming staff birthdays for team recognition

### 10.5 Compliance Tracking

**Navigation:** Human Resources → **Compliance** tab

Track staff document compliance:
- Driver's licenses
- Medical certificates
- Safety training
- Background checks
- Professional certifications

Each document type shows:
- Status (Valid, Expiring, Expired, Missing)
- Expiry date
- Upload date
- Alert thresholds

### 10.6 Staff Import

**Navigation:** Human Resources → **Import** tab **(Admin only)**

- **Upload CSV/Excel** — Bulk import staff records
- **Field Mapping** — Map file columns to staff fields
- **Validation** — Preview and fix errors before import
- **Overwrite Option** — Choose whether to update existing records

---

## 11. Analytics

The Analytics section provides dashboards and reports for organizational performance insights.

### 11.1 Analytics Dashboard

**Navigation:** Sidebar → **Analytics** → **Analytics Dashboard**

![Analytics Dashboard](../screenshots/complete/30-analytics-dashboard.png)
*Figure 11.1: Analytics Dashboard showing project metrics, team performance, and trend charts*

#### Components

- **Statistics Cards** — Key metrics at a glance (projects, completions, revenue, issues)
- **Daily Progress Chart** — Visual timeline of daily progress across projects
- **Project Status View** — Distribution of projects by status
- **Team Performance Table** — Staff productivity metrics
- **Key Insights** — AI-generated insights and recommendations

### 11.2 Enhanced KPIs

**Navigation:** Sidebar → **Analytics** → **Enhanced KPIs**

Advanced Key Performance Indicator tracking with:
- Custom KPI definitions
- Target vs actual tracking
- Trend visualization over time
- Drill-down by project, team, or period

### 11.3 KPI Dashboard

**Navigation:** Sidebar → **Analytics** → **KPI Dashboard**

A focused view of the most important operational KPIs:
- Installation completion rates
- Maintenance response times
- QA pass rates
- Financial metrics

### 11.4 Reports

**Navigation:** Sidebar → **Analytics** → **Reports**

Generate and export operational reports:
- **Project Reports** — Progress, timeline adherence, budget
- **Staff Reports** — Productivity, attendance, compliance
- **Financial Reports** — Revenue, expenses, profitability
- **Operational Reports** — Ticket volumes, SLA compliance

### 11.5 Technician Performance **(ENHANCED)**

New analytics for field technician performance:

#### Technician Directory

- **Flexible Date Filters** — Custom date ranges for performance analysis
- **Edit Modal** — Update technician information directly from analytics
- **Performance Differentiation** — Separate metrics for installers vs activators

#### Performance Metrics

- **dB Signal Quality** — Track signal strength measurements by installer
- **Installation Statistics** — Completion rates, time per installation
- **Activation Statistics** — Success rates, activation times
- **WhatsApp Integration** — Import technician names from WhatsApp contacts

---

## 12. Communications

The Communications section manages WhatsApp integration, meeting coordination, and team notifications.

### 12.1 Communications Portal **(ENHANCED)**

**Navigation:** Sidebar → **Communications** → **Communications Portal**

![Communications](../screenshots/complete/31-communications.png)
*Figure 12.1: Communications Portal showing unified messaging and meetings interface*

The Communications Portal now provides a unified communications hub:
- Overview statistics
- Recent communications
- Notification channels
- Action items from communications
- **Meetings Integration** — Meetings module now fully integrated (no longer separate)

#### Meetings Integration **(MERGED)**

The Meetings module is now part of the Communications Portal, providing:
- **Fireflies.ai Sync** — Automatically synced meeting transcripts
- **Meeting Summaries** — AI-generated summaries with key points
- **Action Items** — Tasks extracted from meeting discussions
- **Participant Tracking** — Meeting attendance and history
- **Access Control** — Participant-based access (only see meetings you attended)
- **Super Admin Override** — Super admins can access all meetings regardless of participation

### 12.2 WhatsApp Administration

**(Admin only)**

**Navigation:** Sidebar → **Communications** → **WhatsApp Portal**

![WhatsApp Admin](../screenshots/complete/32-whatsapp-admin.png)
*Figure 12.2: WhatsApp Administration showing groups, message logs, and service health*

#### Tabs

| Tab | Purpose |
|-----|---------|
| **Groups** | Manage WhatsApp project groups |
| **Logs** | View message delivery logs with export |
| **Templates** | Manage message templates |
| **Services** | Monitor WhatsApp service health (Sender, Bridge, Feedback) |
| **Settings** | Configure WhatsApp integration settings |

#### Key Features

- **Group Management** — Create and manage WhatsApp groups per project
- **Message Logs** — Search, filter, and export message history
- **Template Management** — Create reusable message templates
- **Service Health** — Monitor the health of WhatsApp infrastructure:
  - **Sender** (port 8081) — Sends outgoing messages
  - **Bridge** (port 8083) — Receives DR submissions
  - **Feedback** (port 8092) — Sends QA feedback

### 12.3 PDF Tools

**Navigation:** Sidebar → **Communications** → **PDF Tools**

A collection of PDF manipulation tools:
- Merge PDFs
- Split PDFs
- Convert documents to PDF
- Compress PDFs
- Rotate pages
- Add watermarks

### 12.4 Help Center & AI Chat Assistant **(NEW)**

FibreFlow includes a comprehensive Help Center with an AI-powered chat assistant to provide instant support and documentation access.

**Navigation:** Sidebar → **Communications** → **Help Center**

![Help Center](../screenshots/complete/36-help-center.png)
*Figure 12.3: Help Center showing searchable documentation with AI Chat Widget*

#### Features

**Searchable Documentation:**
- **Table of Contents Sidebar** — Navigate documentation sections easily with an organized sidebar
- **Full-Text Search** — Find answers quickly by searching across all help articles
- **Module-Specific Guides** — Detailed documentation organized by FibreFlow module
- **Step-by-Step Tutorials** — Visual walkthroughs with screenshots for common tasks
- **FAQ Section** — Frequently asked questions with quick answers

**AI Chat Widget:**
The floating chat button is available on every page in FibreFlow, providing instant AI assistance:

- **Always Available** — Accessible from any page via the floating chat icon
- **Topic-Scoped Conversations** — Choose from 13 specialized topics:
  - Dashboard
  - Projects
  - Activate
  - Fleet
  - Maintenance
  - Procurement
  - Assets
  - HR
  - Analytics
  - Communications
  - QField QA
  - System Administration
  - General Help

- **Quick Question Suggestions** — Each topic includes pre-configured quick questions relevant to that area
- **Multi-Turn Conversations** — Ask follow-up questions to dive deeper into topics
- **Conversation History** — Review previous questions and answers within the current session
- **Context-Aware Responses** — AI understands FibreFlow terminology and workflows

#### Using the AI Chat Assistant

1. **Access the Chat** — Click the floating chat icon (visible on all pages)
2. **Select Topic** — Choose the relevant topic from the dropdown (e.g., "Activate" for QA questions)
3. **Ask Your Question** — Type your question or click a suggested quick question
4. **Review Response** — The AI provides detailed answers with references to documentation
5. **Follow Up** — Ask clarifying questions to get more specific information
6. **Switch Topics** — Change topics anytime to get help with different modules

> **Tip:** The AI Chat Assistant is trained on FibreFlow documentation and can help with navigation, feature explanations, troubleshooting, and best practices.

#### Access Control

- **Available to All Roles** — The Help Center and AI Chat are accessible to all users regardless of role
- **Role-Appropriate Answers** — The AI tailors responses based on your role and permissions
- **No Sensitive Data** — The chat assistant focuses on help documentation and does not access your project data

> **Important:** While the AI Chat Assistant is very helpful, it provides guidance based on documentation. For system-specific issues or data problems, contact your system administrator.

---

## 13. System Administration

The System section provides administrative tools for monitoring, data management, and configuration.

**(Admin only — most features)**

### 13.1 System Health Hub

**Navigation:** Sidebar → **System** → **System Health Hub**

![System Health](../screenshots/complete/33-system-health.png)
*Figure 13.1: System Health Hub showing service status, API health, and recent alerts*

Monitor the health of all FibreFlow services:
- **API Health** — Status of all API endpoints
- **Database** — Connection pool status and query performance
- **External Services** — VLM, QContact, Smartsheet, OneMap connectivity
- **Job Queue** — Background task processing status
- **Error Tracking** — Recent errors and their frequency

### 13.2 Data Sync **(ENHANCED)**

**Navigation:** Sidebar → **System** → **Data Sync**

![Data Sync](../screenshots/complete/34-data-sync.png)
*Figure 13.2: Data Sync page showing sync operations, OLT report, and operation history*

#### Granular Tab-Level Permissions **(NEW)**

Data Sync now uses **granular tab-level permissions**:
- Users only see sync groups their role has access to
- Loading spinner prevents flash of unauthorized content
- Permissions checked client-side for instant filtering

#### Sync Groups

| Group | Description | Access Level |
|-------|-------------|-------------|
| **Activate** | OES Sync, SharePoint Sync — Activate QA data imports | System Admin |
| **QField** | QField Sync — Push coordinates for field mapping | System Admin |
| **History** | Operation history and audit logs | System Admin |
| **OLT Report** | Import and fix ONT serial mismatches from OLT reports | System Admin |
| **1Map Sync** | Sync serial numbers with 1Map (OneMap) | System Admin |
| **QContact Sync** | Maintenance ticket synchronization | System Admin |

#### OLT Report (Enhanced Feature)

The OLT Report tool manages ONT serial number corrections with comprehensive enhancements:

1. **Import OLT mismatch report** (Excel)
2. **View mismatched records** (wrong serial in 1Map)
3. **Auto-fix** — System corrects serials in 1Map via API with:
   - **Cross-DR Conflict Detection** — Identifies when fixing one DR would create conflicts with other DRs
   - **Swap Feature UI** — Visual interface for swapping serials between conflicting DRs:
     - Shows both DRs involved in the conflict
     - Preview of proposed swap
     - One-click swap execution
     - Automatic validation after swap
   - **UPS Transfer Capabilities** — Transfer UPS equipment between DRs:
     - Identify UPS misplacements
     - Transfer UPS to correct DR
     - Automatic photo re-sync after UPS transfer
     - Validation of UPS serial uniqueness
   - **Photo Synchronization** — Photos automatically re-synced after serial fixes:
     - ONT photos transferred to correct DR
     - UPS photos moved with UPS transfers
     - Photo metadata updated
     - Maintains photo audit trail
   - **Investigation Context Cards** — Rich contextual information for troubleshooting

4. **Enhanced Investigation** — Detailed investigation workflow with:
   - **Collapsible Context Cards** — Expandable information panels for:
     - DR details
     - Serial history
     - Photo timeline
     - Related conflicts
   - **Status Mismatch Detection** — Identifies discrepancies between:
     - OLT report status
     - 1Map activation status
     - FibreFlow DR status
   - **Photo Copying Between DRs** — Transfer photos when equipment is reassigned:
     - Smart photo selection
     - Metadata preservation
     - Audit trail maintained
   - **Live Match/Mismatch Counts** — Real-time statistics during investigation:
     - Total records processed
     - Matches found
     - Mismatches identified
     - Conflicts detected

5. **Comprehensive Reporting** — Enhanced reporting capabilities:
   - **CSV Export for All Sub-Tabs**:
     - Mismatches tab export
     - Conflicts tab export
     - Displaced ONTs export
     - Investigation history export
     - Custom field selection
   - **Date Filters for Statistics Cards**:
     - Filter stats by date range
     - Compare periods
     - Trend analysis
   - **Clickable Status Filters on Stats Cards**:
     - Click any stat card to filter the list
     - Quick filtering by status
     - Combined filter support
   - **Sub-Status Filter on Investigate Tab**:
     - Filter by specific sub-status (e.g., "Pending Swap", "Photo Sync Required")
     - Advanced filtering for complex investigations
   - **Smart Displaced Badges**:
     - Visual indicators for displaced ONTs
     - Color-coded by displacement severity
     - Quick identification of problematic records
   - **Displaced ONT Tracking**:
     - Dedicated tracking for ONTs found in wrong locations
     - History of displacement events
     - Resolution workflow

> **Important:** When swapping serials between DRs, always verify the photos are transferred correctly. The system automatically handles photo re-sync, but visual confirmation is recommended for critical installations.

### 13.3 VLM Learning **(NEW)**

**Navigation:** Sidebar → **System** → **VLM Learning**

FibreFlow now includes an enterprise-wide VLM (Vision Language Model) learning system:

#### Features

- **Human-in-the-Loop (HITL) Corrections** — Users can correct AI mistakes to improve accuracy
- **Learning Across Modules** — Corrections in one module improve AI performance system-wide
- **Confidence Scoring** — All VLM operations include confidence scores
- **Correction Tracking** — Track which corrections have been applied and their impact
- **Model Performance** — Monitor improvement in AI accuracy over time

#### Supported Modules

VLM Learning integrates with:
- **Fleet** — License disc OCR, odometer reading, fuel gauge scanning
- **Procurement** — PO document extraction, receipt scanning
- **Activate** — Photo categorization, serial number extraction
- **QField QA** — Photo validation and compliance checking
- **Assets** — Asset label verification

### 13.4 Infrastructure

**Navigation:** Sidebar → **System** → **Infrastructure**

Monitor FibreFlow infrastructure:
- Server status (Production, Staging, Dev)
- Service health checks
- Resource utilization
- Links to external monitoring (xyOps, Grafana) — **Currently hidden**

### 13.5 Settings

**Navigation:** Sidebar → **System** → **Settings**

![Settings](../screenshots/complete/35-settings.png)
*Figure 13.3: Settings page showing organizational, procurement, and user preference tabs*

#### Settings Tabs

| Tab | Content |
|-----|---------|
| **General** | Organization name, branding, defaults |
| **Procurement** | Approval thresholds, default terms, tax rates |
| **User Preferences** | Sidebar customization, theme, notifications |
| **Positions** | Manage staff positions |
| **Departments** | Manage department list |
| **Hierarchy** | Reporting structure configuration |

#### Sidebar Customization

Users can customize their sidebar by:
1. Go to **Settings** → **User Preferences**
2. Select which sections to show/hide
3. Reorder sections by drag-and-drop
4. Save preferences (stored per user)

### 13.6 Imports & Downloads

**Navigation:** Sidebar → **System** → **Imports** / **Downloads** — **Currently hidden**

- **Imports** — SOW document import with data extraction
- **Downloads** — Export templates, reports, and data extracts

---

## 14. Appendices

### Appendix A: What's New in Version 1.3

This section summarizes the major changes and new features since version 1.2 (February 10, 2026).

#### New Features (Version 1.3)

| Feature | Module | Description |
|---------|--------|-------------|
| **Help Center & AI Chat** | Communications | Searchable documentation with AI chat assistant, 13 topic categories, multi-turn conversations |
| **Duplicate Serial Detection** | Activate | Auto-detect duplicate ONT/UPS serials, bold mismatch warnings, missing serial prompts |
| **Fireflies Speakers Integration** | Communications | Enhanced participant tracking using Fireflies speakers data |
| **PP Data Enhancements** | Activate | 12 local data sources (up from 3), maintenance ticket creation, live progress tracking |
| **QField Bulk Assignment** | Field Operations | Due dates and priority levels for bulk photo assignments |
| **Fuel Gauge Scanning** | Fleet | VLM extraction of fuel percentage from dashboard photos |
| **OLT Report Enhancements** | System | Cross-DR swap UI, UPS transfers, CSV exports, clickable filters, displaced badges |

#### Enhanced Features (Version 1.3)

- **Meetings Participant Matching** — Improved name-based matching for non-admin users
- **Enhanced Attendee Display** — Better participant lists in Communications portal
- **Pole Number Display** — Improved pole number visibility on QField QA photo cards
- **Photo-to-Pole Mapping** — Automatic geographic context for field photos
- **Tank Level Field** — Added to portal fuel fill-up form with gauge integration
- **Sub-Status Filters** — Investigation tab filtering by sub-status
- **Live Progress Tracking** — Real-time progress bars during 1Map serial lookups

#### User Interface Improvements (Version 1.3)

- **AI Chat Widget** — Floating chat button available on all pages
- **Help Center Sidebar** — Table of contents navigation for documentation
- **Enhanced Warning Display** — Bold 🔴 formatting for critical serial mismatches
- **Collapsible Context Cards** — Expandable panels in OLT investigation
- **Smart Displaced Badges** — Color-coded severity indicators for displaced ONTs
- **Clickable Status Cards** — Click statistics cards to filter lists

#### System Enhancements (Version 1.3)

- **12 PP Data Sources** — Expanded from 3 to 12 local serial matching sources
- **Photo Re-Sync** — Automatic photo synchronization after OLT fixes and UPS transfers
- **Cross-DR Conflict Detection** — Identifies serial swap conflicts before execution
- **CSV Export for All OLT Tabs** — Comprehensive export capabilities
- **Date-Filtered Statistics** — OLT report stats with date range filtering
- **Real-Time Validation** — Duplicate detection during DR acknowledgment workflow

---

### Appendix A.1: What's New in Version 1.2

Version 1.2 changes (February 10, 2026):

#### New Features (Version 1.2)

| Feature | Module | Description |
|---------|--------|-------------|
| **PP Data Management** | Activate | Pre-provisioned ONT import, resolution, and Excel export |
| **Company Verification** | Contractors | CIPC verification, ID validation, criminal checks for contractors |
| **QField QA System** | Field Operations | AI-powered photo validation with real-time feedback |
| **Granular Access Control** | System | Tab-level permissions across multiple modules |
| **Client PO Management** | Projects | PDF import, VAT breakdown, activation requirements |
| **Documents Tab** | Projects | Centralized file uploads for project documentation |
| **VLM Learning System** | System | Enterprise-wide AI learning with human corrections |
| **Meetings Integration** | Communications | Meetings merged into Communications Portal |
| **Fleet Enhancements** | Fleet | Manager visibility for check-ins, enhanced OCR |

#### User Interface Improvements (Version 1.2)

- **Mobile Responsive Design** — 28 files updated for mobile readiness
- **Dark Theme Conversions** — Multiple modules converted to dark theme
- **Tab Scrollability** — Mobile-friendly tab navigation
- **Enhanced Navigation** — Field Operations section added
- **Simplified Staff Creation** — Name, email, phone only with auto-generated IDs

#### System Enhancements (Version 1.2)

- **Master Build Agreement** — Renamed from Master Service Agreement
- **Excel Export Filters** — PP Data export with project/status filters
- **Enhanced OLT Reports** — Cross-DR conflict detection and resolution
- **Improved Error Handling** — Better logging and user feedback
- **Security Hardening** — Multiple security improvements implemented

### Appendix B: Role Permissions Matrix

| Module | Super Admin | Admin | Manager | Technician | Viewer | Contractor |
|--------|:-----------:|:-----:|:-------:|:----------:|:------:|:----------:|
| Dashboard | Full | Full | Full | View | View | — |
| Projects | Full | Full | Full | View | View | Assigned |
| Clients | Full | Full | Full | — | View | — |
| Contractors | Full | Full | Full | — | View | Own |
| Activate | Full | Full | Full | — | View | — |
| Field Operations | Full | Full | Full | Assigned | View | — |
| Maintenance | Full | Full | Full | Assigned | View | — |
| Procurement | Full | Full | Full | — | View | — |
| Assets | Full | Full | Full | Checkout | View | — |
| Fleet | Full | Full | Full | Own | View | — |
| HR / Staff | Full | Full | View | Own | — | — |
| Analytics | Full | Full | Full | — | View | — |
| Communications | Full | Full | View | — | View | — |
| WhatsApp Admin | Full | Full | — | — | — | — |
| System Admin | Full | — | — | — | — | — |
| Settings | Full | Full | Limited | — | — | — |

**Legend:** Full = All CRUD operations | View = Read only | Assigned = Only assigned items | Own = Only own records | — = No access

### Appendix C: Keyboard Shortcuts

| Shortcut | Action |
|----------|--------|
| **Tab** | Navigate between form fields |
| **Shift+Tab** | Navigate backwards between fields |
| **Escape** | Close modal or cancel action |
| **Ctrl+Enter** | Submit form |
| **Ctrl+K** | Open global search (where available) |
| **/** | Focus search bar (on list pages) |

### Appendix D: Glossary of Terms

| Term | Definition |
|------|-----------|
| **BOQ** | Bill of Quantities — itemized list of materials for a project |
| **DR** | Drop Reference — unique identifier for a fiber drop point (e.g., DR1738371) |
| **FT Number** | FiberTime reference number from QContact (e.g., FT695563) |
| **GRN** | Goods Receipt Note — document confirming receipt of ordered items |
| **HITL** | Human-in-the-Loop — AI learning system with human corrections |
| **KPI** | Key Performance Indicator — measurable metric for tracking performance |
| **Master Build Agreement** | Renamed from Master Service Agreement |
| **OES** | Operation Engineering Support — Nokia activation data |
| **OLT** | Optical Line Terminal — equipment at the service provider end |
| **ONT** | Optical Network Terminal — customer premises equipment |
| **PO** | Purchase Order — formal order to a supplier |
| **PON** | Passive Optical Network — fiber distribution network |
| **PP Data** | Pre-Provisioned Data — ONT serials registered before activation |
| **QA** | Quality Assurance — verification process for installations |
| **QContact** | FiberTime's CRM system (fibertime.qcontact.com) |
| **QField** | Mobile GIS application for field mapping |
| **RBAC** | Role-Based Access Control — permission system |
| **RFQ** | Request for Quotation — invitation for suppliers to bid |
| **SLA** | Service Level Agreement — response time target |
| **SOW** | Scope of Work — project scope document defining work |
| **VLM** | Vision Language Model — AI for analyzing photos (Qwen3-VL) |
| **VPS** | Virtual Private Server — remote server infrastructure |

### Appendix E: System Architecture

#### Environments

| Environment | URL | Purpose |
|-------------|-----|---------|
| **Production** | app.fibreflow.app | Live system |
| **Staging** | vf.fibreflow.app | Pre-release testing |
| **Development** | dev.fibreflow.app | Feature development |
| **Backup** | backup.fibreflow.app | Redundancy |

#### External Integrations

| System | Purpose | Sync Method |
|--------|---------|-------------|
| **QContact** | Maintenance CRM | API (bidirectional) |
| **Smartsheet** | Pipeline tracking | API (import) |
| **Fireflies.ai** | Meeting transcription | API (import) |
| **1Map / OneMap** | GIS data (drops, photos) | API (bidirectional) |
| **QField** | Mobile GIS mapping | GeoJSON push, plugin integration |
| **Odoo** | ERP (inventory, POs) | API (import) |
| **Firebase** | File storage | SDK |
| **SharePoint** | Document sync | API (import) |
| **SearchWorks** | Company verification | API (CIPC, ID validation) |
| **MinIO** | Photo storage | Docker integration |

### Appendix F: Troubleshooting Guide

#### General Issues

| Problem | Solution |
|---------|----------|
| **Page not loading** | Refresh the page. Check your internet connection. Try clearing browser cache. |
| **"Unauthorized" error** | Your session may have expired. Log out and log back in. |
| **Missing menu items** | Your role may not have access. Contact your administrator. |
| **Data not updating** | Try refreshing the page. Some data syncs on intervals (e.g., QContact). |
| **Slow performance** | Check your internet speed. Try a different browser. Close unnecessary tabs. |
| **Dark mode issues** | Toggle theme in header menu. Some older browsers may have display issues. |

#### Module-Specific Issues

| Module | Problem | Solution |
|--------|---------|----------|
| **Activate** | Photos not loading | Check if the 1Map API is responding. Photos require VPS connectivity. |
| **Activate** | VLM categorization wrong | Correct the categorization manually — corrections improve future accuracy. |
| **Activate** | PP Data not importing | Ensure OES Excel file has "PP DATA" sheet with correct format. |
| **Field Operations** | QField QA photos missing | Check MinIO connectivity and photo path format with version suffixes. |
| **Field Operations** | AI validation stuck | Check VLM service at port 8100. Verify logger format in API calls. |
| **Maintenance** | QContact sync failed | Check Data Sync tab for error details. Try manual sync. |
| **Maintenance** | Cannot move ticket status | Check required fields (fault cause, verification). Verify RBAC permissions. |
| **Procurement** | BOQ import fails | Ensure Excel has headers in row 1. Check column mapper for correct mappings. |
| **Procurement** | PO stuck in approval | Check Approvals tab. The assigned approver may need to take action. |
| **Fleet** | Plate scan not recognized | Ensure good lighting and clear plate photo. Enter plate manually if needed. |
| **Fleet** | Check-in not visible to manager | Ensure user has manager role. Check RBAC permissions. |
| **Assets** | Cannot delete asset | Assets must be checked in (status: Available) before deletion. |
| **HR** | Import errors | Check CSV formatting. Required fields: first_name, last_name, email. |
| **HR** | Missing staff tabs | Check granular permissions. User may not have access to specific tabs. |
| **Communications** | Meetings not showing | Check participant access. Users only see meetings they attended. |
| **Communications** | AI Chat not responding | Refresh page. Check internet connection. AI Chat requires active connection. |
| **Communications** | Help Center search not working | Try different keywords. Use topic filter. Some content may be recently added. |
| **System** | Data Sync tabs missing | Check granular permissions. Loading spinner indicates permission check. |

---

*This manual is maintained by the Velocity Fibre development team. For questions, corrections, or feature requests, contact the system administrator.*

*Document generated: 11 February 2026*`;

export interface ManualSection {
  id: string;
  title: string;
  content: string;
  subsections: ManualSubsection[];
}

export interface ManualSubsection {
  id: string;
  title: string;
  content: string;
}

export interface SearchResult {
  sectionId: string;
  sectionTitle: string;
  subsectionId?: string;
  subsectionTitle?: string;
  content: string;
  matchedText: string;
}

/**
 * Parse the manual content into sections
 */
export function parseManualSections(): ManualSection[] {
  if (!MANUAL_CONTENT) return [];
  
  const lines = MANUAL_CONTENT.split('\n');
  const sections: ManualSection[] = [];
  
  let currentSection: ManualSection | null = null;
  let currentSubsection: ManualSubsection | null = null;
  let contentBuffer: string[] = [];
  
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    
    // Main section (## N. Title)
    if (line.match(/^## \d+\./)) {
      // Save previous content
      if (currentSubsection) {
        currentSubsection.content = contentBuffer.join('\n').trim();
      } else if (currentSection) {
        currentSection.content = contentBuffer.join('\n').trim();
      }
      
      // Save previous section
      if (currentSection) {
        if (currentSubsection) {
          currentSection.subsections.push(currentSubsection);
        }
        sections.push(currentSection);
      }
      
      // Start new section
      const title = line.replace(/^## \d+\.\s*/, '');
      currentSection = {
        id: slugify(title),
        title,
        content: '',
        subsections: []
      };
      currentSubsection = null;
      contentBuffer = [];
    }
    // Subsection (### Title)
    else if (line.match(/^###\s+/)) {
      // Save previous subsection content
      if (currentSubsection) {
        currentSubsection.content = contentBuffer.join('\n').trim();
        if (currentSection) {
          currentSection.subsections.push(currentSubsection);
        }
      } else if (currentSection) {
        // Save section content before first subsection
        currentSection.content = contentBuffer.join('\n').trim();
      }
      
      // Start new subsection
      const title = line.replace(/^###\s*/, '');
      currentSubsection = {
        id: slugify(title),
        title,
        content: ''
      };
      contentBuffer = [];
    }
    // Other section header (## without number) - skip these for now
    else if (line.match(/^##\s+/) && !line.match(/^## \d+\./)) {
      // Skip non-numbered sections like "Table of Contents"
      continue;
    }
    // Regular content
    else {
      contentBuffer.push(line);
    }
  }
  
  // Save the last section/subsection
  if (currentSubsection) {
    currentSubsection.content = contentBuffer.join('\n').trim();
    if (currentSection) {
      currentSection.subsections.push(currentSubsection);
    }
  } else if (currentSection) {
    currentSection.content = contentBuffer.join('\n').trim();
  }
  
  if (currentSection) {
    sections.push(currentSection);
  }
  
  return sections.filter(section => section.title.length > 0);
}

/**
 * Search through the manual content
 */
export function searchManual(query: string, sections: ManualSection[]): SearchResult[] {
  if (!query.trim()) return [];
  
  const results: SearchResult[] = [];
  const searchTerms = query.toLowerCase().split(' ');
  
  sections.forEach(section => {
    // Search in section content
    const sectionContent = section.content.toLowerCase();
    const matchesSection = searchTerms.every(term => sectionContent.includes(term));
    
    if (matchesSection && section.content.trim()) {
      const matchIndex = sectionContent.indexOf(searchTerms[0]);
      const context = extractContext(section.content, matchIndex, 200);
      
      results.push({
        sectionId: section.id,
        sectionTitle: section.title,
        content: section.content,
        matchedText: context
      });
    }
    
    // Search in subsections
    section.subsections.forEach(subsection => {
      const subsectionContent = subsection.content.toLowerCase();
      const matchesSubsection = searchTerms.every(term => subsectionContent.includes(term));
      
      if (matchesSubsection && subsection.content.trim()) {
        const matchIndex = subsectionContent.indexOf(searchTerms[0]);
        const context = extractContext(subsection.content, matchIndex, 200);
        
        results.push({
          sectionId: section.id,
          sectionTitle: section.title,
          subsectionId: subsection.id,
          subsectionTitle: subsection.title,
          content: subsection.content,
          matchedText: context
        });
      }
    });
  });
  
  return results;
}

/**
 * Create URL-friendly slug from text
 */
function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^\w\s-]/g, '')
    .replace(/[\s_-]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

/**
 * Extract context around a match
 */
function extractContext(content: string, matchIndex: number, contextLength: number): string {
  const start = Math.max(0, matchIndex - contextLength / 2);
  const end = Math.min(content.length, matchIndex + contextLength / 2);
  
  let context = content.substring(start, end);
  
  // Trim to word boundaries
  if (start > 0) {
    const firstSpace = context.indexOf(' ');
    if (firstSpace > 0) {
      context = '...' + context.substring(firstSpace);
    }
  }
  
  if (end < content.length) {
    const lastSpace = context.lastIndexOf(' ');
    if (lastSpace > 0 && lastSpace < context.length - 10) {
      context = context.substring(0, lastSpace) + '...';
    }
  }
  
  return context;
}

export default MANUAL_CONTENT;
