/**
 * Scoped Snag Report — Excel Workbook Builder
 *
 * Pure function: no DB, no HTTP, no side effects.
 * Produces a 3-sheet workbook (Summary / Snags / Scope) from pre-fetched
 * SnagReportScopeRow[].  All dates written as ISO YYYY-MM-DD strings
 * per feedback_excel_date_format.
 */

import * as XLSX from 'xlsx';
import type { SnagReportMeta, SnagReportScopeRow } from './snagReportRenderer';

// ── Internal helpers ──────────────────────────────────────────────────────────

/**
 * Truncates an ISO datetime string or Date to a YYYY-MM-DD date string.
 * Satisfies feedback_excel_date_format: ISO only, no locale strings.
 */
function isoDate(ts: string | Date): string {
  if (ts instanceof Date) return ts.toISOString().slice(0, 10);
  return ts.slice(0, 10);
}

/** Resolved statuses that count as "done" for the summary KPI. */
const RESOLVED_STATUSES = new Set(['resolved', 'verified', 'closed']);

// ── Workbook builder ──────────────────────────────────────────────────────────

/**
 * Builds a 3-sheet Excel workbook for a scoped snag report.
 *
 * Sheets:
 *  - Summary  — report metadata + KPI counts (one label/value pair per row)
 *  - Snags    — flat row per snag with ISO dates
 *  - Scope    — the filter parameters that produced this report
 *
 * @param meta   Report metadata (numbers, dates, scope filters, generated-by).
 * @param rows   Pre-fetched snag rows — same shape the POST route produces.
 * @returns      An xlsx WorkBook ready for XLSX.write().
 */
export function buildScopeSnagWorkbook(
  meta: SnagReportMeta,
  rows: SnagReportScopeRow[],
): XLSX.WorkBook {
  const wb = XLSX.utils.book_new();

  // ── Aggregations ─────────────────────────────────────────────────────────

  const bySev = rows.reduce<Record<string, number>>((acc, r) => {
    acc[r.severity] = (acc[r.severity] ?? 0) + 1;
    return acc;
  }, {});

  const resolved = rows.filter(r => RESOLVED_STATUSES.has(r.status)).length;

  // ── Sheet 1: Summary ──────────────────────────────────────────────────────

  const summaryData: Array<{ label: string; value: string | number }> = [
    { label: 'Report number', value: meta.reportNumber },
    { label: 'Project',       value: meta.projectName },
    { label: 'Generated at',  value: isoDate(meta.generatedAt) },
    { label: 'Generated by',  value: meta.generatedBy },
    { label: 'Scope',         value: meta.scope },
    { label: 'From',          value: meta.fromDate },
    { label: 'To',            value: meta.toDate },
    { label: 'Total snags',   value: rows.length },
    { label: 'Critical',      value: bySev.critical ?? 0 },
    { label: 'Major',         value: bySev.major ?? 0 },
    { label: 'Minor',         value: bySev.minor ?? 0 },
    { label: 'Resolved',      value: resolved },
  ];

  XLSX.utils.book_append_sheet(
    wb,
    XLSX.utils.json_to_sheet(summaryData),
    'Summary',
  );

  // ── Sheet 2: Snags ────────────────────────────────────────────────────────

  const snagsData = rows.map(r => ({
    zone_no:        r.zone_no,
    pon_no:         r.pon_no,
    pole_number:    r.pole_number,
    category:       r.category,
    severity:       r.severity,
    status:         r.status,
    description:    r.description,
    noc_ticket_uid: r.noc_ticket_uid,
    created_at:     isoDate(r.created_at),
  }));

  XLSX.utils.book_append_sheet(
    wb,
    XLSX.utils.json_to_sheet(snagsData),
    'Snags',
  );

  // ── Sheet 3: Scope ────────────────────────────────────────────────────────

  const scopeData: Array<{ label: string; value: string }> = [
    { label: 'zones',      value: meta.zones.join(', ') },
    { label: 'pons',       value: meta.pons.join(', ') },
    { label: 'poles',      value: meta.poles.join(', ') },
    { label: 'severities', value: meta.severities.join(', ') },
    { label: 'categories', value: meta.categories.join(', ') },
  ];

  XLSX.utils.book_append_sheet(
    wb,
    XLSX.utils.json_to_sheet(scopeData),
    'Scope',
  );

  return wb;
}
