/**
 * Accounting section configuration
 *
 * Sage-aligned navigation with Phase 1 additions:
 * - Recurring Invoices, Write-Offs, Adjustments under Customers
 * - Batch Payments, Adjustments under Suppliers
 * - Recurring Journals under Accounts
 * - New VAT section
 */

import {
  Calculator, BookOpen, FileSpreadsheet, BarChart3,
  Receipt, Wallet, Clock, CreditCard, FileText,
  Landmark, Database, TrendingDown, Upload,
  Users, ShoppingCart, ArrowLeftRight, Settings,
  DollarSign, FileCheck, ClipboardList, PieChart,
  Scale, CalendarCheck, BookMarked, Banknote,
  Repeat, XCircle, SlidersHorizontal, Layers,
  RotateCcw, Percent,
} from 'lucide-react';
import type { NavSection } from './types';

export const accountingSection: NavSection = {
  section: 'ACCOUNTING',
  sectionId: 'accounting',
  isCollapsible: true,
  defaultExpanded: true,
  items: [
    {
      to: '/accounting',
      icon: Calculator,
      label: 'Dashboard',
      shortLabel: 'Dash',
      permissions: [],
      rbacKey: 'accounting',
    },
    // ── Customers (Sage: Customers menu) ─────────────
    {
      to: '#',
      icon: Users,
      label: 'Customers',
      shortLabel: 'Cust',
      permissions: [],
      rbacKey: 'accounting',
      isGroup: true,
      subItems: [
        {
          to: '/accounting/customer-invoices',
          icon: FileText,
          label: 'Tax Invoices',
          shortLabel: 'Inv',
          permissions: [],
          rbacKey: 'accounting',
        },
        {
          to: '/accounting/recurring-invoices',
          icon: Repeat,
          label: 'Recurring Invoices',
          shortLabel: 'Recur',
          permissions: [],
          rbacKey: 'accounting',
        },
        {
          to: '/accounting/customer-payments',
          icon: CreditCard,
          label: 'Receipts',
          shortLabel: 'Rcpt',
          permissions: [],
          rbacKey: 'accounting',
        },
        {
          to: '/accounting/credit-notes',
          icon: FileCheck,
          label: 'Credit Notes',
          shortLabel: 'CN',
          permissions: [],
          rbacKey: 'accounting',
        },
        {
          to: '/accounting/write-offs',
          icon: XCircle,
          label: 'Write-Offs',
          shortLabel: 'WO',
          permissions: [],
          rbacKey: 'accounting',
        },
        {
          to: '/accounting/adjustments?type=customer',
          icon: SlidersHorizontal,
          label: 'Adjustments',
          shortLabel: 'Adj',
          permissions: [],
          rbacKey: 'accounting',
        },
        {
          to: '/accounting/ar-aging',
          icon: Clock,
          label: 'Aging',
          shortLabel: 'ARAge',
          permissions: [],
          rbacKey: 'accounting',
        },
        {
          to: '/accounting/customer-statements',
          icon: ClipboardList,
          label: 'Statements',
          shortLabel: 'Stmt',
          permissions: [],
          rbacKey: 'accounting',
        },
      ],
    },
    // ── Suppliers (Sage: Suppliers menu) ──────────────
    {
      to: '#',
      icon: ShoppingCart,
      label: 'Suppliers',
      shortLabel: 'Supp',
      permissions: [],
      rbacKey: 'accounting',
      isGroup: true,
      subItems: [
        {
          to: '/accounting/supplier-invoices',
          icon: Receipt,
          label: 'Invoices',
          shortLabel: 'SI',
          permissions: [],
          rbacKey: 'accounting',
        },
        {
          to: '/accounting/supplier-payments',
          icon: Wallet,
          label: 'Payments',
          shortLabel: 'SPay',
          permissions: [],
          rbacKey: 'accounting',
        },
        {
          to: '/accounting/batch-payments',
          icon: Layers,
          label: 'Batch Payments',
          shortLabel: 'Batch',
          permissions: [],
          rbacKey: 'accounting',
        },
        {
          to: '/accounting/supplier-returns',
          icon: TrendingDown,
          label: 'Returns',
          shortLabel: 'Ret',
          permissions: [],
          rbacKey: 'accounting',
        },
        {
          to: '/accounting/adjustments?type=supplier',
          icon: SlidersHorizontal,
          label: 'Adjustments',
          shortLabel: 'Adj',
          permissions: [],
          rbacKey: 'accounting',
        },
        {
          to: '/accounting/ap-aging',
          icon: Clock,
          label: 'Aging',
          shortLabel: 'APAge',
          permissions: [],
          rbacKey: 'accounting',
        },
      ],
    },
    // ── Banking (Sage: Banking menu) ─────────────────
    {
      to: '#',
      icon: Landmark,
      label: 'Banking',
      shortLabel: 'Bank',
      permissions: [],
      rbacKey: 'accounting',
      isGroup: true,
      subItems: [
        {
          to: '/accounting/bank-accounts',
          icon: Landmark,
          label: 'Bank Accounts',
          shortLabel: 'Accts',
          permissions: [],
          rbacKey: 'accounting',
        },
        {
          to: '/accounting/bank-reconciliation/import',
          icon: Upload,
          label: 'Import Statement',
          shortLabel: 'Import',
          permissions: [],
          rbacKey: 'accounting',
        },
        {
          to: '/accounting/bank-reconciliation',
          icon: FileSpreadsheet,
          label: 'Reconcile',
          shortLabel: 'Recon',
          permissions: [],
          rbacKey: 'accounting',
        },
        {
          to: '/accounting/bank-transfers',
          icon: ArrowLeftRight,
          label: 'Transfers',
          shortLabel: 'Xfer',
          permissions: [],
          rbacKey: 'accounting',
        },
      ],
    },
    // ── Accounts (Sage: Accounts + Accountant's Area) ─
    {
      to: '#',
      icon: BookOpen,
      label: 'Accounts',
      shortLabel: 'Acct',
      permissions: [],
      rbacKey: 'accounting',
      isGroup: true,
      subItems: [
        {
          to: '/accounting/chart-of-accounts',
          icon: BookOpen,
          label: 'Chart of Accounts',
          shortLabel: 'CoA',
          permissions: [],
          rbacKey: 'accounting',
        },
        {
          to: '/accounting/journal-entries',
          icon: FileSpreadsheet,
          label: 'Journal Entries',
          shortLabel: 'JE',
          permissions: [],
          rbacKey: 'accounting',
        },
        {
          to: '/accounting/recurring-journals',
          icon: RotateCcw,
          label: 'Recurring Journals',
          shortLabel: 'RJ',
          permissions: [],
          rbacKey: 'accounting',
        },
        {
          to: '/accounting/fiscal-periods',
          icon: CalendarCheck,
          label: 'Fiscal Periods',
          shortLabel: 'FP',
          permissions: [],
          rbacKey: 'accounting',
        },
        {
          to: '/accounting/default-accounts',
          icon: Settings,
          label: 'Default Accounts',
          shortLabel: 'Dflt',
          permissions: [],
          rbacKey: 'accounting',
        },
      ],
    },
    // ── VAT (Sage: Accountant's Area > VAT) ──────────
    {
      to: '#',
      icon: Percent,
      label: 'VAT',
      shortLabel: 'VAT',
      permissions: [],
      rbacKey: 'accounting',
      isGroup: true,
      subItems: [
        {
          to: '/accounting/reports/vat-return',
          icon: DollarSign,
          label: 'VAT Return',
          shortLabel: 'VRtn',
          permissions: [],
          rbacKey: 'accounting',
        },
        {
          to: '/accounting/vat-adjustments',
          icon: SlidersHorizontal,
          label: 'VAT Adjustments',
          shortLabel: 'VAdj',
          permissions: [],
          rbacKey: 'accounting',
        },
      ],
    },
    // ── Accountant's Area (Sage: Accountant's Area) ──
    {
      to: '#',
      icon: Scale,
      label: "Accountant's Area",
      shortLabel: 'CPA',
      permissions: [],
      rbacKey: 'accounting',
      isGroup: true,
      subItems: [
        {
          to: '/accounting/trial-balance',
          icon: Scale,
          label: 'Trial Balance',
          shortLabel: 'TB',
          permissions: [],
          rbacKey: 'accounting',
        },
        {
          to: '/accounting/opening-balances',
          icon: BookMarked,
          label: 'Opening Balances',
          shortLabel: 'OB',
          permissions: [],
          rbacKey: 'accounting',
        },
        {
          to: '/accounting/year-end',
          icon: CalendarCheck,
          label: 'Year-End',
          shortLabel: 'YE',
          permissions: [],
          rbacKey: 'accounting',
        },
      ],
    },
    // ── Reports (Sage: Reports menu) ─────────────────
    {
      to: '#',
      icon: BarChart3,
      label: 'Reports',
      shortLabel: 'Rpt',
      permissions: [],
      rbacKey: 'accounting',
      isGroup: true,
      subItems: [
        {
          to: '/accounting/reports/income-statement',
          icon: BarChart3,
          label: 'Income Statement',
          shortLabel: 'P&L',
          permissions: [],
          rbacKey: 'accounting',
        },
        {
          to: '/accounting/reports/balance-sheet',
          icon: PieChart,
          label: 'Balance Sheet',
          shortLabel: 'BS',
          permissions: [],
          rbacKey: 'accounting',
        },
        {
          to: '/accounting/reports/cash-flow',
          icon: Banknote,
          label: 'Cash Flow',
          shortLabel: 'CF',
          permissions: [],
          rbacKey: 'accounting',
        },
        {
          to: '/accounting/reports/budget-vs-actual',
          icon: BarChart3,
          label: 'Budget vs Actual',
          shortLabel: 'Budg',
          permissions: [],
          rbacKey: 'accounting',
        },
        {
          to: '/accounting/reports/project-profitability',
          icon: BarChart3,
          label: 'Project Profitability',
          shortLabel: 'Profit',
          permissions: [],
          rbacKey: 'accounting',
        },
      ],
    },
    // ── Settings ─────────────────────────────────────
    {
      to: '/accounting/sage-migration',
      icon: Database,
      label: 'Data Import',
      shortLabel: 'Import',
      permissions: [],
      rbacKey: 'accounting',
    },
  ],
};
