import { useCallback, useEffect, useState } from 'react';
import { AppLayout } from '@/components/layout/AppLayout'; import { ModulePage } from '@/components/module-page'; import { fleetConfig } from '@/modules/navigation';
import type { AssignmentOptions } from '@/modules/fleet/assignments/rosterQueries'; import type { AssignmentRosterEntry } from '@/modules/fleet/assignments/types';
import { assignmentApi } from '@/modules/fleet/assignments/web/assignmentApi'; import { AssignmentEditor } from '@/modules/fleet/assignments/web/AssignmentEditor'; import { AssignmentFilters, type AssignmentFilterValue } from '@/modules/fleet/assignments/web/AssignmentFilters'; import { AssignmentRoster } from '@/modules/fleet/assignments/web/AssignmentRoster'; import { ProjectSiteManager } from '@/modules/fleet/assignments/web/ProjectSiteManager';
const date = () => new Date().toISOString().slice(0, 10); const empty: AssignmentOptions = { staff: [], teams: [], projects: [], sites: [], vehicles: [] };
export default function AssignmentPage() {
  const [filters, setFilters] = useState<AssignmentFilterValue>({ from: date(), to: date(), projectId: '', siteId: '', source: '' }); const [rows, setRows] = useState<AssignmentRosterEntry[]>([]); const [options, setOptions] = useState(empty); const [selected, setSelected] = useState<string[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [history, setHistory] = useState<Record<string, unknown>[] | null>(null);
  const query = useCallback(() => new URLSearchParams(Object.entries(filters).filter(([, value]) => value)).toString(), [filters]);
  const load = useCallback(async () => { setLoading(true); try { const value = query(); const [roster, opts] = await Promise.all([assignmentApi.roster(value), assignmentApi.options(value)]); setRows(roster.items); setOptions(opts); setError(null); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Could not load assignments'); } finally { setLoading(false); } }, [query]);
  useEffect(() => { void load(); }, [load]); const ids = selected.filter((id) => rows.some((row) => row.assignmentId === id));
  async function copy() { try { await assignmentApi.copyPreview(ids, filters.from); setError('Copy preview prepared; review it before committing.'); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Copy failed'); } }
  async function end() { try { await Promise.all(ids.map((id) => assignmentApi.update(id, { action: 'end', endDate: filters.to, reason: 'Ended from roster workspace' }))); setSelected([]); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : 'End failed'); } }
  async function showHistory() { if (ids.length !== 1) return; try { setHistory(await assignmentApi.history(ids[0]!)); } catch (caught) { setError(caught instanceof Error ? caught.message : 'History failed'); } }
  return <AppLayout><ModulePage config={fleetConfig} hideTabs><div className="p-6 space-y-4"><h1>Operational assignments</h1><AssignmentFilters value={filters} onChange={setFilters} />{error && <p role="alert">{error}</p>}<AssignmentRoster rows={rows} selected={selected} onSelect={setSelected} loading={loading} /><div className="flex gap-2"><button disabled={!ids.length} onClick={() => void copy()}>Copy roster</button><button disabled={!ids.length} onClick={() => void end()}>End selected</button><button disabled={ids.length !== 1} onClick={() => void showHistory()}>View history</button></div>{history && <pre aria-label="Assignment history">{JSON.stringify(history, null, 2)}</pre>}<AssignmentEditor options={options} projectId={filters.projectId} siteId={filters.siteId} from={filters.from} to={filters.to} onCommitted={load} />{filters.projectId && <ProjectSiteManager onCreate={async (site) => { await assignmentApi.createSite({ ...site, projectId: filters.projectId }); await load(); }} />}</div></ModulePage></AppLayout>;
}
