import { useCallback, useEffect, useState } from 'react';
import { AppLayout } from '@/components/layout/AppLayout'; import { ModulePage } from '@/components/module-page'; import { fleetConfig } from '@/modules/navigation';
import type { AssignmentOptions, AssignmentRosterItem } from '@/modules/fleet/assignments/rosterQueries';
import { assignmentApi } from '@/modules/fleet/assignments/web/assignmentApi'; import { AssignmentEditor } from '@/modules/fleet/assignments/web/AssignmentEditor'; import { AssignmentFilters, type AssignmentFilterValue } from '@/modules/fleet/assignments/web/AssignmentFilters'; import { AssignmentRoster } from '@/modules/fleet/assignments/web/AssignmentRoster'; import { ProjectSiteManager } from '@/modules/fleet/assignments/web/ProjectSiteManager';
const date = () => new Date().toISOString().slice(0, 10); const empty: AssignmentOptions = { staff: [], teams: [], projects: [], sites: [], vehicles: [] };
export default function AssignmentPage() {
  const [filters, setFilters] = useState<AssignmentFilterValue>({ from: date(), to: date(), projectId: '', siteId: '', source: '' }); const [rows, setRows] = useState<AssignmentRosterItem[]>([]); const [options, setOptions] = useState(empty); const [selected, setSelected] = useState<string[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [history, setHistory] = useState<Record<string, unknown>[] | null>(null); const [page, setPage] = useState(1); const [total, setTotal] = useState(0); const [actionPending, setActionPending] = useState(false);
  const query = useCallback((includePage = true) => { const params = new URLSearchParams(Object.entries(filters).filter(([, value]) => value)); if (includePage) params.set('page', String(page)); return params.toString(); }, [filters, page]);
  const load = useCallback(async () => { setLoading(true); try { const opts = await assignmentApi.options(query(false)); setOptions(opts); if (!filters.projectId) { setRows([]); setTotal(0); setError(null); return; } const roster = await assignmentApi.roster(query()); setRows(roster.items); setTotal(roster.total); setSelected((current) => current.filter((id) => roster.items.some((row) => row.assignmentId === id))); setError(null); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Could not load assignments'); } finally { setLoading(false); } }, [query, filters.projectId]);
  useEffect(() => { void load(); }, [load]); const ids = selected;
  async function copy() { setActionPending(true); try { const preview = await assignmentApi.copyPreview(ids, filters.from); if (preview.conflicts.some((item) => item.level === 'blocking')) throw new Error('Copied roster has blocking conflicts'); await assignmentApi.commit(preview.normalizedRows, preview, preview.conflicts.some((item) => item.level === 'warning')); setSelected([]); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Copy failed'); } finally { setActionPending(false); } }
  async function end() { if (ids.length !== 1) return; setActionPending(true); try { await assignmentApi.update(ids[0]!, { action: 'end', endDate: filters.to, reason: 'Ended from roster workspace' }); setSelected([]); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : 'End failed'); } finally { setActionPending(false); } }
  async function showHistory() { if (ids.length !== 1) return; try { setHistory(await assignmentApi.history(ids[0]!)); } catch (caught) { setError(caught instanceof Error ? caught.message : 'History failed'); } }
  return <AppLayout><ModulePage config={fleetConfig} hideTabs><div className="p-6 space-y-4"><h1>Operational assignments</h1><AssignmentFilters value={filters} options={options} onChange={(value) => { setPage(1); setFilters(value); }} />{error && <p role="alert">{error}</p>}{!filters.projectId ? <p>Select a project to load its roster.</p> : <AssignmentRoster rows={rows} selected={selected} onSelect={setSelected} loading={loading} />}<div className="flex gap-2"><button disabled={actionPending || !ids.length} onClick={() => void copy()}>Copy roster</button><button disabled={actionPending || ids.length !== 1} onClick={() => void end()}>End selected</button><button disabled={actionPending || ids.length !== 1} onClick={() => void showHistory()}>View history</button></div>{total > 25 && <div><button disabled={page === 1} onClick={() => setPage((value) => value - 1)}>Previous</button><span> Page {page} </span><button disabled={page * 25 >= total} onClick={() => setPage((value) => value + 1)}>Next</button></div>}{history && <pre aria-label="Assignment history">{JSON.stringify(history, null, 2)}</pre>}<AssignmentEditor options={options} projectId={filters.projectId} siteId={filters.siteId} from={filters.from} to={filters.to} onCommitted={load} />{filters.projectId && <ProjectSiteManager onCreate={async (site) => { await assignmentApi.createSite({ ...site, projectId: filters.projectId }); await load(); }} />}</div></ModulePage></AppLayout>;
}
