"""
Lawley PDF Report Generator - Using BOSS PDF Skill patterns

This module implements PDF generation following the BOSS PDF Skill best practices:
- Template-based approach
- Clean separation of concerns
- Reusable components
- Easy to maintain and extend

Based on: ~/.claude/skills/document-processing/pdf/SKILL.md
"""

from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.units import mm
from reportlab.lib.enums import TA_CENTER, TA_RIGHT
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    HRFlowable, Image, KeepTogether, PageBreak
)
from reportlab.pdfgen import canvas
from io import BytesIO
from datetime import datetime
from typing import Dict, List, Optional, Any
import logging

logger = logging.getLogger(__name__)


class NumberedCanvas(canvas.Canvas):
    """Custom canvas for page numbers and headers/footers."""

    def __init__(self, *args, **kwargs):
        canvas.Canvas.__init__(self, *args, **kwargs)
        self._saved_page_states = []
        self._report_date = kwargs.get('report_date', '')

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        """Add page numbers to each page."""
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_header_footer(num_pages)
            canvas.Canvas.showPage(self)
        canvas.Canvas.save(self)

    def draw_header_footer(self, page_count):
        """Draw header and footer on each page."""
        page_num = self._pageNumber
        width, height = A4

        # Footer
        self.setFont('Helvetica', 8)
        self.setFillColor(colors.HexColor('#7f8c8d'))
        self.drawString(15*mm, 10*mm, f"Generated by BOSS | {datetime.now().strftime('%Y-%m-%d %H:%M')}")
        self.drawRightString(width - 15*mm, 10*mm, f"Page {page_num} of {page_count}")


class LawleyPDFGenerator:
    """
    PDF Generator for Lawley Daily Performance Reports.

    Implements BOSS PDF Skill patterns:
    - Template-based generation
    - Modular components
    - Consistent styling
    - Easy to extend
    """

    def __init__(self):
        """Initialize PDF generator with styles."""
        self.styles = self._create_styles()
        self.colors = self._define_colors()

    def _define_colors(self) -> Dict[str, colors.HexColor]:
        """Define color scheme for the report."""
        return {
            'primary': colors.HexColor('#3498db'),
            'success': colors.HexColor('#27ae60'),
            'warning': colors.HexColor('#f39c12'),
            'danger': colors.HexColor('#e74c3c'),
            'dark': colors.HexColor('#2c3e50'),
            'light_gray': colors.HexColor('#ecf0f1'),
            'medium_gray': colors.HexColor('#95a5a6'),
            'text_gray': colors.HexColor('#7f8c8d'),
        }

    def _create_styles(self) -> Dict[str, ParagraphStyle]:
        """Create custom paragraph styles."""
        base_styles = getSampleStyleSheet()

        return {
            'title': ParagraphStyle(
                'CustomTitle',
                parent=base_styles['Title'],
                fontSize=18,
                textColor=colors.HexColor('#2c3e50'),
                spaceAfter=12,
                alignment=TA_CENTER
            ),
            'heading1': ParagraphStyle(
                'CustomHeading1',
                parent=base_styles['Heading1'],
                fontSize=14,
                textColor=colors.HexColor('#2c3e50'),
                spaceAfter=6,
                spaceBefore=12,
                borderPadding=(0, 0, 3, 0),
                borderColor=colors.HexColor('#3498db'),
                borderWidth=2
            ),
            'heading2': ParagraphStyle(
                'CustomHeading2',
                parent=base_styles['Heading2'],
                fontSize=12,
                textColor=colors.HexColor('#34495e'),
                spaceAfter=4,
                spaceBefore=8
            ),
            'normal': base_styles['Normal'],
            'centered': ParagraphStyle(
                'Centered',
                parent=base_styles['Normal'],
                alignment=TA_CENTER
            ),
        }

    def generate_report(
        self,
        output_path: str,
        metrics: Dict[str, Any],
        charts: Dict[str, BytesIO],
        ai_commentary: Optional[Dict[str, str]] = None
    ) -> bool:
        """
        Generate complete Lawley PDF report.

        Args:
            output_path: Where to save the PDF
            metrics: All extracted metrics from Excel
            charts: Dictionary of chart BytesIO objects
            ai_commentary: AI-generated insights

        Returns:
            True if successful, False otherwise
        """
        try:
            # Extract data
            ao = metrics.get('area_overview', {})
            pm = metrics.get('period_metrics', {})
            trends = metrics.get('trends', {})
            daily_comp = metrics.get('daily_comparison', [])
            pon_level = metrics.get('pon_level', {})

            report_date = ao.get('date', datetime.now().strftime('%Y-%m-%d'))

            # Create document
            doc = SimpleDocTemplate(
                output_path,
                pagesize=A4,
                rightMargin=15*mm,
                leftMargin=15*mm,
                topMargin=20*mm,
                bottomMargin=20*mm
            )

            # Build story
            story = []

            # Title page
            story.extend(self._build_title_page(report_date, ao))

            # Executive scorecard
            story.extend(self._build_scorecard(ao, pm, trends))

            # Key metrics table
            story.extend(self._build_metrics_table(ao, pm))

            # Charts section
            if charts:
                story.extend(self._build_charts_section(charts, daily_comp))

            # AI Commentary
            if ai_commentary:
                story.extend(self._build_ai_commentary(ai_commentary))

            # PON Infrastructure
            story.extend(self._build_pon_section(pon_level))

            # Build PDF
            doc.build(
                story,
                canvasmaker=lambda *args, **kwargs: NumberedCanvas(
                    *args, report_date=report_date, **kwargs
                )
            )

            logger.info(f"PDF report generated: {output_path}")
            return True

        except Exception as e:
            logger.error(f"Error generating PDF report: {e}")
            import traceback
            traceback.print_exc()
            return False

    def _build_title_page(self, report_date: str, ao: Dict) -> List:
        """Build the title page."""
        elements = []

        # Main title
        title_text = f"<b>LAWLEY DAILY PERFORMANCE REPORT</b>"
        elements.append(Paragraph(title_text, self.styles['title']))
        elements.append(Spacer(1, 5*mm))

        # Date info
        date_text = f"<b>Report Date:</b> {report_date}"
        elements.append(Paragraph(date_text, self.styles['centered']))

        generated_text = f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}"
        elements.append(Paragraph(generated_text, self.styles['centered']))
        elements.append(Spacer(1, 10*mm))

        # Separator
        elements.append(HRFlowable(
            width="100%",
            thickness=2,
            color=self.colors['primary'],
            spaceBefore=5*mm,
            spaceAfter=5*mm
        ))

        return elements

    def _build_scorecard(self, ao: Dict, pm: Dict, trends: Dict) -> List:
        """Build executive scorecard with key metrics."""
        elements = []

        elements.append(Paragraph("EXECUTIVE SCORECARD", self.styles['heading1']))
        elements.append(Spacer(1, 3*mm))

        # Extract values
        homes = ao.get('homes_connected', 0)
        homes_change = ao.get('homes_change', 0)
        trphc = ao.get('trphc', 0)
        trphc_vs_30 = trends.get('trphc_vs_30day', 0)
        ab_ratio = ao.get('ab_hc_ratio', 0)
        bundle_gap = ao.get('bundle_gap', 0)

        avg_30day = pm.get('avg_30day', {})
        trphc_30day_avg = avg_30day.get('trphc', 0)

        # Status indicators
        def get_status(value, threshold_good, threshold_ok):
            if value >= threshold_good:
                return ('✓', self.colors['success'])
            elif value >= threshold_ok:
                return ('~', self.colors['warning'])
            else:
                return ('✗', self.colors['danger'])

        growth_status = get_status(homes_change, 20, 5)
        trphc_status = get_status(trphc, trphc_30day_avg * 1.1, trphc_30day_avg * 0.9)
        ab_status = get_status(ab_ratio, 0.80, 0.65)
        gap_status = ('⚠', self.colors['warning']) if bundle_gap > homes * 0.25 else ('✓', self.colors['success'])

        # Scorecard table
        scorecard_data = [
            ['Metric', 'Value', 'Change'],
            [
                Paragraph('<b>Homes Connected</b>', self.styles['normal']),
                Paragraph(f"<font color='{growth_status[1].hexval()}'>{growth_status[0]}</font> {homes:,}", self.styles['normal']),
                Paragraph(f"{'▲' if homes_change >= 0 else '▼'} {homes_change:+,} vs day before", self.styles['normal'])
            ],
            [
                Paragraph('<b>TRPHC</b>', self.styles['normal']),
                Paragraph(f"<font color='{trphc_status[1].hexval()}'>{trphc_status[0]}</font> R{trphc:.2f}", self.styles['normal']),
                Paragraph(f"{'▲' if trphc_vs_30 >= 0 else '▼'} R{trphc_vs_30:+.2f} vs 30d", self.styles['normal'])
            ],
            [
                Paragraph('<b>Bundle Ratio</b>', self.styles['normal']),
                Paragraph(f"<font color='{ab_status[1].hexval()}'>{ab_status[0]}</font> {ab_ratio:.1%}", self.styles['normal']),
                Paragraph("Target: 85%", self.styles['normal'])
            ],
            [
                Paragraph('<b>Bundle Gap</b>', self.styles['normal']),
                Paragraph(f"<font color='{gap_status[1].hexval()}'>{gap_status[0]}</font> {bundle_gap:,}", self.styles['normal']),
                Paragraph(f"{bundle_gap/homes*100:.1f}% of homes", self.styles['normal'])
            ],
        ]

        scorecard_table = Table(scorecard_data, colWidths=[60*mm, 60*mm, 60*mm])
        scorecard_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), self.colors['primary']),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('TOPPADDING', (0, 0), (-1, -1), 8),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
            ('GRID', (0, 0), (-1, -1), 0.5, self.colors['medium_gray']),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, self.colors['light_gray']]),
        ]))

        elements.append(scorecard_table)
        elements.append(Spacer(1, 8*mm))

        return elements

    def _build_metrics_table(self, ao: Dict, pm: Dict) -> List:
        """Build key metrics comparison table."""
        elements = []

        elements.append(Paragraph("KEY METRICS COMPARISON", self.styles['heading1']))
        elements.append(Spacer(1, 3*mm))

        avg_21day = pm.get('avg_21day', {})
        avg_30day = pm.get('avg_30day', {})

        metrics_data = [
            ['Metric', 'Yesterday', 'vs Day Before', '21-Day Avg', '30-Day Avg'],
            [
                'Homes Connected',
                f"{ao.get('homes_connected', 0):,}",
                f"{ao.get('homes_change', 0):+,}",
                f"{avg_21day.get('homes', 0):,.0f}",
                f"{avg_30day.get('homes', 0):,.0f}"
            ],
            [
                'Revenue',
                f"R {ao.get('revenue', 0):,.2f}",
                f"R {ao.get('revenue_change', 0):+,.2f}",
                f"R {avg_21day.get('revenue', 0):,.2f}",
                f"R {avg_30day.get('revenue', 0):,.2f}"
            ],
            [
                'TRPHC',
                f"R {ao.get('trphc', 0):.2f}",
                f"R {ao.get('trphc_yesterday', 0):.2f}",
                f"R {avg_21day.get('trphc', 0):.2f}",
                f"R {avg_30day.get('trphc', 0):.2f}"
            ],
            [
                'Active Bundles',
                f"{ao.get('active_bundles', 0):,}",
                '-',
                f"{avg_21day.get('active_bundles', 0):,.0f}",
                f"{avg_30day.get('active_bundles', 0):,.0f}"
            ],
        ]

        metrics_table = Table(metrics_data, colWidths=[40*mm, 35*mm, 35*mm, 35*mm, 35*mm])
        metrics_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), self.colors['primary']),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (0, -1), 'LEFT'),
            ('ALIGN', (1, 0), (-1, -1), 'RIGHT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 9),
            ('TOPPADDING', (0, 0), (-1, -1), 6),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
            ('GRID', (0, 0), (-1, -1), 0.5, self.colors['medium_gray']),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, self.colors['light_gray']]),
        ]))

        elements.append(metrics_table)
        elements.append(Spacer(1, 8*mm))

        return elements

    def _build_charts_section(self, charts: Dict, daily_comp: List) -> List:
        """Build charts section."""
        elements = []

        elements.append(PageBreak())
        elements.append(Paragraph("PERFORMANCE VISUALIZATION", self.styles['heading1']))
        elements.append(Spacer(1, 3*mm))

        # 7-day comparison chart
        if charts.get('7day_comparison'):
            elements.append(Paragraph("7-Day Performance Trend", self.styles['heading2']))
            elements.append(Spacer(1, 2*mm))

            chart_img = Image(charts['7day_comparison'], width=170*mm, height=80*mm)
            elements.append(chart_img)
            elements.append(Spacer(1, 5*mm))

        # Rolling average charts (multi-metric)
        if charts.get('multi_metric_rolling'):
            elements.append(PageBreak())
            elements.append(Paragraph("Rolling Average Trends - All Metrics", self.styles['heading2']))
            elements.append(Spacer(1, 2*mm))

            multi_img = Image(charts['multi_metric_rolling'], width=180*mm, height=110*mm)
            elements.append(multi_img)
            elements.append(Spacer(1, 5*mm))

        return elements

    def _build_ai_commentary(self, ai_commentary: Dict) -> List:
        """Build AI commentary section."""
        elements = []

        elements.append(PageBreak())
        elements.append(Paragraph("AI-GENERATED INSIGHTS", self.styles['heading1']))
        elements.append(Spacer(1, 3*mm))

        # Executive Summary
        if ai_commentary.get('executive_summary'):
            elements.append(Paragraph("<b>Executive Summary:</b>", self.styles['normal']))
            elements.append(Spacer(1, 2*mm))
            elements.append(Paragraph(ai_commentary['executive_summary'], self.styles['normal']))
            elements.append(Spacer(1, 4*mm))

        # Key Highlights
        if ai_commentary.get('key_highlights'):
            elements.append(Paragraph("<b>Key Highlights:</b>", self.styles['normal']))
            elements.append(Spacer(1, 2*mm))
            for highlight in ai_commentary['key_highlights']:
                elements.append(Paragraph(f"• {highlight}", self.styles['normal']))
            elements.append(Spacer(1, 4*mm))

        # Full commentary if available
        if ai_commentary.get('full_commentary'):
            elements.append(Paragraph("<b>Detailed Analysis:</b>", self.styles['normal']))
            elements.append(Spacer(1, 2*mm))

            # Split into paragraphs
            paragraphs = ai_commentary['full_commentary'].split('\n\n')
            for para in paragraphs:
                if para.strip():
                    elements.append(Paragraph(para.strip(), self.styles['normal']))
                    elements.append(Spacer(1, 3*mm))

        return elements

    def _build_pon_section(self, pon_level: Dict) -> List:
        """Build PON infrastructure section."""
        elements = []

        elements.append(PageBreak())
        elements.append(Paragraph("NETWORK INFRASTRUCTURE", self.styles['heading1']))
        elements.append(Spacer(1, 3*mm))

        pon_data = [
            ['Metric', 'Value'],
            ['Total PONs', f"{pon_level.get('total_pons', 0)} active"],
            ['Average PON Age', f"{pon_level.get('avg_pon_age', 0):.1f} days"],
            ['Homes per PON', f"{pon_level.get('avg_homes_per_pon', 0):.1f} average"],
        ]

        pon_table = Table(pon_data, colWidths=[80*mm, 80*mm])
        pon_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), self.colors['primary']),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (0, -1), 'LEFT'),
            ('ALIGN', (1, 0), (-1, -1), 'RIGHT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('TOPPADDING', (0, 0), (-1, -1), 8),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
            ('GRID', (0, 0), (-1, -1), 0.5, self.colors['medium_gray']),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, self.colors['light_gray']]),
        ]))

        elements.append(pon_table)

        return elements
